version: '3.8'

services:
  realcommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
    container_name: realcommerce-frontend
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production

  realcommerce-lojavirtual:
    build:
      context: ./lojavirtual
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
    container_name: realcommerce-lojavirtual
    ports:
      - "8081:80"
    restart: always
    environment:
      - NODE_ENV=production