[infNFe]
versao=4.00

[Identificacao]
cNF=90384591                                                      
natOp=VENDA USUARIO FINAL
indPag=0
mod=55
serie=1
nNF=11
dhEmi=07/05/2022 11:31:50
dhSaiEnt=
tpNF=1
idDest=1
tpAmb=2
tpImp=1
tpEmis=1
finNFe=1
indFinal=0
indPres=1
procEmi=0
indIntermed=
verProc=SGMaster22
dhCont=0
xJust=

; O Grupo "NFeRef" deve ser preenchido apenas se existir documentos Referenciados na NFe (Tipos aceitos: NFE, CTE, ECF, NFP, NF)

[NFRef001]
Tipo=
refNFe=
cUF=
AAMM=
CNPJ=
mod=
Serie=
nNF=
CNPJCPF=
IE=
refCTe=
ModECF=
nECF=
nCOO=

[Emitente]
CRT=1
CNPJCPF=32126214000103
xNome=TIAGO FERREIRA LEME 39234784880
xFant=FERREIRA CENTRO AUTOMOTIVO
IE=225310593110
IEST=
IM=
CNAE=
xLgr=AV ANTONIETA THOMAZINI LONZA
nro=2079
xCpl=********
xBairro=PARQUE BRASIL
cMun=3507605
xMun=BRAGANCA PAULISTA
cUF=35
UF=SP
CEP=12906320
cPais=1058
xPais=BRASIL
Fone=1122773336
cMunFG=3507605

; O Grupo "Avulsa" deve ser preenchido apenas para emissão de Nota Avulsa

[Avulsa]
CNPJ=
xOrgao=
matr=
xAgente=
fone=
UF=
nDAR=
dEmi=
vDAR=
repEmi=
dPag=

[Destinatario]
idEstrangeiro=
CNPJCPF=02016898000111
xNome=UNIWELD INDUSTRIA DE ELETRODOS LTDA
indIEDest=1
IE=225.108.855.113
ISUF=
Email=compras@uniweld.com.br
xLgr=AVENIDA QUINZE DE DEZEMBRO
nro=1788
xCpl=
xBairro=MATADOURO
cMun=3507605
xMun=BRAGANCA PAULISTA
UF=SP
CEP=12910691
cPais=1058
xPais=BRASIL
Fone=1140356411

; O Grupo "Retirada" deve ser preenchido se existir os dados do responsável pela Retirada da Mercadoria

[Retirada]
CNPJCPF=
xNome=
xLgr=
nro=
xCpl=
xBairro=
cMun=
xMun=
UF=
CEP=
PaisCod=
Pais=
Fone=
Email=
IE=

; O Grupo "Entrega" deve ser preenchido se existir os dados do responsável pela Entrega da Mercadoria

[Entrega]
CNPJCPF=
xNome=
xLgr=
nro=
xCpl=
xBairro=
cMun=
xMun=
UF=
CEP=
PaisCod=
Pais=
Fone=
Email=
IE=

; O Grupo "autXML" deve ser preenchido se existir alguém autorizado a Consultar a NFe (Ex: CNPJ do Contador)
; índice: 01-10

[autXML01]
CNPJCPF=

[Produto001]
cProd=773
cEAN=SEM GTIN
cEANTrib=SEM GTIN
cBarra=
xProd=215 50 R17 GOODYEAR
NCM=40111000
CEST=1600100
EXTIPI=
CFOP=5405
uCom=UN
qCom=2.0000
vUnCom=580.0002000000
vProd=1160.00
cBarraTrib=
uTrib=UN
qTrib=2.0000
vUnTrib=580.0000000000
vFrete=0.00
vSeg=0.00
vDesc=0.00
vOutro=0.00
indTot=1
xPed=
nItemPed=
nFCI=
nRECOPI=
pDevol=
vIPIDevol=
vTotTrib=413.77
infAdProd=
indEscala=
CNPJFab=
cBenef=

; O Grupo "NVE" deve ser preenchido se existir código do mesmo para o produto

[NVE001001]
NVE=

; O Grupo "DI" deve ser preenchido se o produto for de Importação

[DI001001]
nDi=
dDi=
xLocDesemb=
UFDesemb=
dDesemb=
tpViaTransp=
vAFRMM=
tpIntermedio=
CNPJ=
UFTerceiro=
cExportador=

; O Grupo "LADI" deve ser preenchido se existir o grupo DI para o produto

[LADI001001001]
nAdicao=
nSeqAdi=
cFabricante=
vDescDI=
nDraw=

; O Grupo "detExport" deve ser preenchido se o produto for de Exportação

[detExport001001]
nDraw=
nRE=
chNFe=
qExport=

; O Grupo "Rastro" deve ser preenchido apenas para produto rastreado conforme especificações técnicas

[rastro001001]
nLote=
qLote=
dFab=
dVal=
cAgreg=

; O Grupo "Medicamento" deve ser preenchido apenas para NFe de Medicamentos conforme especificações técnicas

[Medicamento001001]
cProdANVISA=
vPMC=
nLote=
qLote=
dFab=
dVal=
vPMC=

; O Grupo "Arma" deve ser preenchido apenas para NFe de Armamentos conforme especificações técnicas

[Arma001001]
nSerie=
tpArma=
nCano=
descr=

; O Grupo "impostoDevol" deve ser preenchido se existir imposto de Devolução para NFe

[impostoDevol001]
pDevol=
vIPIDevol=

; O Grupo "Veiculo" deve ser preenchido apenas se houver necessidade da informação na NF-e conforme especificações técnicas

[Veiculo001]
chassi=
tpOP=
cCor=
xCor=
pot=
Cilin=
pesoL=
pesoB=
nSerie=
tpComb=
nMotor=
CMT=
dist=
anoMod=
anoFab=
tpPint=
tpVeic=
espVeic=
VIN=
condVeic=
cMod=
cCorDENATRAN=
lota=
tpRest=

; O Grupo "Combustivel", "CIDE", "ICMSComb",  deve ser preenchido apenas para NFe de Combustíveis conforme especificações técnicas

[Combustivel001]
cProdANP=
pMixGN=
CODIF=
qTemp=
UFCons=
descANP=
pGLP=
pGNn=
pGNi=
vPart=

[CIDE001]
qBCprod=
vAliqProd=
vCIDE=

[ICMSComb001]
vBCICMS=
vICMS=
vBCICMSST=
vICMSST=

; O Grupo "ICMSInter", deve ser preenchido se exigido conforme especificações técnicas

[ICMSInter001]
vBCICMSSTDest=
vICMSSTDest=

; O Grupo "ICMSCons",  deve ser preenchido se exigido conforme especificações técnicas

[ICMSCons001]
vBCICMSSTCons=
vICMSSTCons=
UFCons=


;Informe este campo apenas para SimplesNacional (CRT=1)
;Informe este campo apenas para Regime Normal (CRT=3)

[ICMS001]
CSOSN=500	                    
orig=0
CST=    
modBC=
pRedBC=
vBC=
pICMS=
vICMS=
modBCST=
pMVAST=
pRedBCST=
vBCST=
pICMSST=
vICMSST=
UFST=
pBCOp=
vBCSTRet=0.00
vICMSSTRet=0.00
motDesICMS=
pCredSN=
vCredICMSSN=
vBCSTDest=
vICMSSTDest=
vICMSDeson=
vICMSOp=
pDif=
vICMSDif=
pST=0.000
vBCFCP=
pFCP=
vFCP=  
vBCFCPST=
pFCPST=  
vFCPST=
vBCFCPSTRet=
pFCPSTRet=  
vFCPSTRet=
pRedBCEfet=
vBCEfet=
pICMSEfet=
vICMSEfet= 
vICMSSubstituto=0.00
vICMSSTDeson=
motDesICMSST=
pFCPDif=
vFCPDif=
vFCPEfet=

; O Grupo "ICMSUFDEST",  deve ser preenchido para ICMS Interestadual conforme especificações técnicas

[ICMSUFDEST001]
vBCUFDest=     
vBCFCPUFDest=  
pFCPUFDest=    
pICMSUFDest=   
pICMSInter=    
pICMSInterPart=
vFCPUFDest=    
vICMSUFDest=   
vICMSUFRemet=  

[IPI001]
CST=99
clEnq=
CNPJProd=
cSelo=
qSelo=
cEnq=999
vBC=0.00
qUnid=
vUnid=
pIPI=0.0000
vIPI=0.00

[II001]
vBC=
vDespAdu=
vII=
vIOF=

[PIS001]
CST=99
vBC=0.00
pPIS=0.0000
qBCProd=
vAliqProd=
vPIS=0.00

[PISST001]
vBC=
pPis=
qBCProd=
vAliqProd=
vPIS=
indSomaPISST=

[COFINS001]
CST=99
vBC=0.00
pCOFINS=0.0000
qBCProd=
vAliqProd=
vCOFINS=0.00

[COFINSST001]
vBC=
pCOFINS=
qBCProd=
vAliqProd=
vCOFINS=
indSomaCOFINSST=

[ISSQN001]
vBC=
vAliq=
vISSQN=
cMunFG=
cListServ=
cSitTrib=
vDeducao=
vDeducao=
vOutro=
vDescIncond=
vDescCond=
vISSRet=
indISS=
cServico=
cMun=
cPais=
nProcesso=
indIncentivo=

[obsContItem001]
xCampo=
xTexto=

[obsFiscoItem001]
xCampo=
xTexto=

[Total]
vBC=0.00
vICMS=0.00
vICMSDeson=0.00
vBCST=0.00
vST=0.00
vProd=1160.00
vFrete=0.00
vSeg=0.00
vDesc=0.00
vII=0.00
vIPI=0.00
vPIS=0.00
vCOFINS=0.00
vOutro=0.00
vNF=1160.00
vTotTrib=413.77
vFCP=0.00
vFCPST=0.00
vFCPSTRet=0.00
vIPIDevol=0.00

[ISSQNtot]
vServ=
vBC=
vISS=
vPIS=
vCOFINS=
dCompet=
vDeducao=
vOutro=
vDescIncond=
vDescCond=
vISSRet=
cRegTrib=

[retTrib]
vRetPIS=
vRetCOFINS=
vRetCSLL=
vBCIRRF=
vIRRF=
vBCRetPrev=
vRetPrev=

[Transportador]
modFrete=9
CNPJCPF=
xNome=
IE=
xEnder=
xMun=
UF=
vServ=0
vBCRet=0
pICMSRet=0
vICMSRet=0
CFOP=
cMunFG=
Placa=
UFPlaca=
RNTC=
vagao=
balsa=

[Reboque001]
placa=
UF=
RNTC=

[Volume001]
qVol=
esp=
Marca=
nVol=
pesoL=
pesoB=

[Lacre001001]
nLacre=

; O Grupo "Fatura", "Duplicata"  deve ser preenchido conforme o Tipo de Pagamento especificado no grupo "Pag"

[Fatura]
nFat=1
vOrig=1160.00
vDesc=0.00
vLiq=1160.00

[Duplicata001]
nDup=001
dVenc=15/06/2022
vDup=580.00

[Duplicata002]
nDup=002
dVenc=15/07/2022
vDup=580.00

[pag001]
tPag=05
vPag=1160.00
indPag=0
xPag=


[infIntermed]
CNPJ=
idCadIntTran=

[DadosAdicionais]
infAdFisco=
infCpl=

[InfAdic001]
xCampo=
xTexto=

[ObsFisco001]
xCampo=
xTexto=

[procRef001]
nProc=
indProc=

; O Grupo "Exporta" deve ser utilizado apenas para NFe de Exportação

[Exporta]
UFSaidaPais=
xLocExporta=
xLocDespacho=

[Compra]
xNEmp=
xPed=
xCont=

; O Grupo "cana" deve ser utilizado especificamente para comercialização de Cana de Açúcar, conforme especificações técnicas

[cana]
safra=
ref=
qTotMes=
qTotAnt=
qTotGer=
vFor=
vTotDed=
vLiqFor=

; O Grupo "forDia" deve ser utilizado apenas quando existir o grupo "cana"

[forDia001]
dia=
qtde=

; O Grupo "deduc" deve ser utilizado se houver valor de dedução na NFe

[deduc001]
xDed=
vDed=

; O grupo "infRespTec" é opcional mas poderá ser exigido por uma UF ou outra, devemos ficar atentos a legislação de cada UF.
; Nas configurações do ACBrMonitor aba: DFe/Resp.Técnico temos os campos ID e Código CSRT, o preenchimento deles só
; será possível mediante cadastro do desenvolvedor junto a SEFAZ.
; Esse cadastro só será necessário nas UF que vierem a exigir o grupo "infRespTec".

[infRespTec]
CNPJ=
xContato=
email=
fone=