-- Migration: Create transferencia and transferencia_item tables and finalization RPC
-- Date: 2026-09-03

CREATE TABLE IF NOT EXISTS public.transferencia (
    transferencia_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_origem_id bigint NOT NULL REFERENCES public.empresa(empresa_id),
    empresa_destino_id bigint NOT NULL REFERENCES public.empresa(empresa_id),
    deposito_origem_id bigint NOT NULL REFERENCES public.deposito(deposito_id),
    deposito_destino_id bigint NOT NULL REFERENCES public.deposito(deposito_id),
    dt_transferencia timestamp with time zone DEFAULT now() NOT NULL,
    observacao text DEFAULT ''::text,
    st_transferencia character varying(20) DEFAULT 'ABERTA'::character varying NOT NULL,
    usuario_cadastro text,
    usuario_finalizacao text,
    dt_criacao timestamp with time zone DEFAULT now() NOT NULL,
    dt_finalizacao timestamp with time zone,
    excluido boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_transferencia_empresa_diff CHECK (empresa_origem_id <> empresa_destino_id)
);

CREATE TABLE IF NOT EXISTS public.transferencia_item (
    transferencia_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transferencia_id bigint NOT NULL REFERENCES public.transferencia(transferencia_id) ON DELETE CASCADE,
    produto_id bigint NOT NULL REFERENCES public.produto(produto_id),
    qt_transferir numeric(15,4) NOT NULL,
    excluido boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_transferencia_item_qt CHECK (qt_transferir > 0)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_transferencia_emp_origem ON public.transferencia (empresa_origem_id);
CREATE INDEX IF NOT EXISTS idx_transferencia_emp_destino ON public.transferencia (empresa_destino_id);
CREATE INDEX IF NOT EXISTS idx_transferencia_st ON public.transferencia (st_transferencia);
CREATE INDEX IF NOT EXISTS idx_transferencia_item_transf ON public.transferencia_item (transferencia_id);
CREATE INDEX IF NOT EXISTS idx_transferencia_item_prod ON public.transferencia_item (produto_id);

-- RLS Policies
ALTER TABLE public.transferencia ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo a transferencia" ON public.transferencia;
CREATE POLICY "Permitir acesso completo a transferencia" ON public.transferencia FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.transferencia_item ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo a transferencia_item" ON public.transferencia_item;
CREATE POLICY "Permitir acesso completo a transferencia_item" ON public.transferencia_item FOR ALL USING (true) WITH CHECK (true);

-- Função RPC para Finalização Transacional da Transferência de Estoque
CREATE OR REPLACE FUNCTION public.fu_finalizar_transferencia_estoque(
    _transferencia_id bigint,
    _usuario_email text DEFAULT NULL::text
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
    v_trans RECORD;
    v_item RECORD;
    v_estoque_fisico numeric;
    v_estoque_reservado numeric;
    v_estoque_disponivel numeric;
    v_user_email text;
    v_item_count int := 0;
BEGIN
    -- 1. Obter e bloquear a transferência (FOR UPDATE)
    SELECT * INTO v_trans
    FROM public.transferencia
    WHERE transferencia_id = _transferencia_id
      AND excluido = false
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'Transferência de estoque não encontrada.');
    END IF;

    -- Verificar status
    IF v_trans.st_transferencia = 'FINALIZADA' THEN
        RETURN jsonb_build_object('error', 'A transferência já foi finalizada.');
    END IF;

    IF v_trans.st_transferencia != 'ABERTA' THEN
        RETURN jsonb_build_object('error', 'A transferência não está com status ABERTA.');
    END IF;

    -- Validar filiais
    IF v_trans.empresa_origem_id = v_trans.empresa_destino_id THEN
        RETURN jsonb_build_object('error', 'A filial de origem deve ser diferente da filial de destino.');
    END IF;

    -- Definir usuário
    v_user_email := COALESCE(_usuario_email, v_trans.usuario_cadastro, 'SISTEMA');

    -- 2. Validar que existe ao menos um item
    SELECT COUNT(*) INTO v_item_count
    FROM public.transferencia_item
    WHERE transferencia_id = _transferencia_id
      AND excluido = false;

    IF v_item_count = 0 THEN
        RETURN jsonb_build_object('error', 'Informe pelo menos um produto.');
    END IF;

    -- 3. Revalidar estoque disponível de todos os produtos na origem
    FOR v_item IN
        SELECT ti.*, p.nome as nm_produto
        FROM public.transferencia_item ti
        JOIN public.produto p ON p.produto_id = ti.produto_id
        WHERE ti.transferencia_id = _transferencia_id
          AND ti.excluido = false
    LOOP
        IF v_item.qt_transferir <= 0 THEN
            RETURN jsonb_build_object('error', 'A quantidade deve ser maior que zero.');
        END IF;

        -- Buscar estoque na origem
        SELECT COALESCE(estoque_fisico, 0), COALESCE(estoque_reservado, 0)
        INTO v_estoque_fisico, v_estoque_reservado
        FROM public.estoque
        WHERE produto_id = v_item.produto_id
          AND deposito_id = v_trans.deposito_origem_id
          AND empresa_id = v_trans.empresa_origem_id;

        IF v_estoque_fisico IS NULL THEN
            v_estoque_fisico := 0;
            v_estoque_reservado := 0;
        END IF;

        v_estoque_disponivel := v_estoque_fisico - v_estoque_reservado;

        IF v_estoque_disponivel < v_item.qt_transferir THEN
            RETURN jsonb_build_object(
                'error', 'Estoque disponível insuficiente para o produto ' || COALESCE(v_item.nm_produto, 'ID ' || v_item.produto_id) || '.'
            );
        END IF;
    END LOOP;

    -- 4. Processar a movimentação no estoque_log
    FOR v_item IN
        SELECT ti.*
        FROM public.transferencia_item ti
        WHERE ti.transferencia_id = _transferencia_id
          AND ti.excluido = false
    LOOP
        -- Garantir que existe o registro de estoque na filial/depósito de destino
        IF NOT EXISTS (
            SELECT 1 FROM public.estoque
            WHERE produto_id = v_item.produto_id
              AND deposito_id = v_trans.deposito_destino_id
              AND empresa_id = v_trans.empresa_destino_id
        ) THEN
            INSERT INTO public.estoque (
                empresa_id, produto_id, deposito_id, estoque_fisico, estoque_reservado, estoque_disponivel, dt_criacao, dt_alteracao
            ) VALUES (
                v_trans.empresa_destino_id, v_item.produto_id, v_trans.deposito_destino_id, 0, 0, 0, now(), now()
            );
        END IF;

        -- 4.1 Inserir Saída na Filial/Depósito de Origem
        INSERT INTO public.estoque_log (
            empresa_id,
            produto_id,
            deposito_id,
            qt_movimento,
            usuario,
            dt_hs_log,
            operacao,
            origem,
            nr_doc
        ) VALUES (
            v_trans.empresa_origem_id,
            v_item.produto_id,
            v_trans.deposito_origem_id,
            -v_item.qt_transferir,
            v_user_email,
            now(),
            'SAIDA',
            'TRANSFERENCIA_ESTOQUE',
            _transferencia_id::text
        );

        -- 4.2 Inserir Entrada na Filial/Depósito de Destino
        INSERT INTO public.estoque_log (
            empresa_id,
            produto_id,
            deposito_id,
            qt_movimento,
            usuario,
            dt_hs_log,
            operacao,
            origem,
            nr_doc
        ) VALUES (
            v_trans.empresa_destino_id,
            v_item.produto_id,
            v_trans.deposito_destino_id,
            +v_item.qt_transferir,
            v_user_email,
            now(),
            'ENTRADA',
            'TRANSFERENCIA_ESTOQUE',
            _transferencia_id::text
        );
    END LOOP;

    -- 5. Atualizar o status do cabeçalho da transferência
    UPDATE public.transferencia
    SET st_transferencia = 'FINALIZADA',
        dt_finalizacao = now(),
        usuario_finalizacao = v_user_email
    WHERE transferencia_id = _transferencia_id;

    RETURN jsonb_build_object('success', true, 'message', 'Transferência finalizada com sucesso.');
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('error', 'Não foi possível finalizar a transferência. Nenhuma movimentação foi realizada: ' || SQLERRM);
END;
$$;
