
-- Add missing columns to produto table
ALTER TABLE public.produto
  ADD COLUMN IF NOT EXISTS linha_id integer,
  ADD COLUMN IF NOT EXISTS subgrupo_id integer,
  ADD COLUMN IF NOT EXISTS ncm varchar(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cest varchar(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mva numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tb_a_origem varchar(1) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS grupo_icms_id integer,
  ADD COLUMN IF NOT EXISTS grupo_ipi_id integer,
  ADD COLUMN IF NOT EXISTS grupo_pis_cofins_id integer,
  ADD COLUMN IF NOT EXISTS pc_ipi numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_frete numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_icms_cred numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_ipi_cred numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_emb numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_seguro numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_st_trib numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_outras_desp numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_pis numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_cofins numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_fcp_st numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_difal_sn numeric(9,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_ipi numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_frete numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_icms_cred numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_ipi_cred numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_emb numeric(9,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_seguro numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_st numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_outras_desp numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_pis numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_cofins numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_fcp_st numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_difal_sn numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_custo numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_custo_medio numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_desconto numeric(9,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_outro numeric(9,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_desconto numeric(9,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pc_multiplicador numeric(10,5) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vl_multiplicador numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS st_promo varchar(1) NOT NULL DEFAULT 'N',
  ADD COLUMN IF NOT EXISTS preco_venda_faturado numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preco_promocional_fat numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS altura numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS comprimento numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS largura numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS area numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS peso_bruto numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS peso_liquido numeric(10,4) NOT NULL DEFAULT 0;

-- Create produto_conversao table
CREATE TABLE IF NOT EXISTS public.produto_conversao (
  conversao_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint NOT NULL,
  empresa_id bigint NOT NULL DEFAULT 1,
  unidade_id varchar(10) NOT NULL DEFAULT '',
  tp_movimento varchar(30) NOT NULL DEFAULT '',
  fator_mult numeric(12,5) NOT NULL DEFAULT 1,
  excluido boolean DEFAULT false,
  dt_cadastro timestamptz DEFAULT now(),
  dt_alteracao timestamptz DEFAULT now()
);

ALTER TABLE public.produto_conversao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Auth can manage produto_conversao"
  ON public.produto_conversao FOR ALL TO authenticated
  USING (true) WITH CHECK (true);
