-- Migration: 20260615110000_create_entrega_and_item.sql
-- Cria as tabelas de entrega e entrega_item, adiciona st_entregue em movimento e configura sequenciador

-- 1. Adiciona coluna st_entregue na tabela movimento
ALTER TABLE public.movimento ADD COLUMN IF NOT EXISTS st_entregue character varying(1) DEFAULT 'N';
ALTER TABLE public.movimento DROP CONSTRAINT IF EXISTS check_st_entregue;
ALTER TABLE public.movimento ADD CONSTRAINT check_st_entregue CHECK (st_entregue IN ('N', 'P', 'S'));

-- 2. Criação da tabela de entregas (Minuta de Entrega)
CREATE TABLE IF NOT EXISTS public.entrega (
    entrega_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    empresa_id integer NOT NULL REFERENCES public.empresa(empresa_id) ON DELETE CASCADE,
    cd_entrega bigint NOT NULL,
    dt_inicio timestamp with time zone NOT NULL DEFAULT now(),
    dt_fim timestamp with time zone,
    rota character varying(100) DEFAULT ''::character varying NOT NULL,
    observacoes text DEFAULT ''::text NOT NULL,
    status character varying(20) DEFAULT 'Pendente'::character varying NOT NULL,
    veiculo_id integer REFERENCES public.cadastro_veiculo(veiculo_id) ON DELETE SET NULL,
    motorista_id integer REFERENCES public.cadastro_motorista(motorista_id) ON DELETE SET NULL,
    excluido boolean DEFAULT false NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now() NOT NULL,
    dt_alteracao timestamp with time zone DEFAULT now() NOT NULL
);

-- Primary Key e restrição de unicidade por empresa
ALTER TABLE ONLY public.entrega DROP CONSTRAINT IF EXISTS entrega_pkey CASCADE;
ALTER TABLE ONLY public.entrega ADD CONSTRAINT entrega_pkey PRIMARY KEY (entrega_id);

ALTER TABLE ONLY public.entrega DROP CONSTRAINT IF EXISTS uq_entrega_empresa_codigo CASCADE;
ALTER TABLE ONLY public.entrega ADD CONSTRAINT uq_entrega_empresa_codigo UNIQUE (empresa_id, cd_entrega);

-- 3. Criação da tabela de itens da entrega (Vínculo Pedido <> Entrega)
CREATE TABLE IF NOT EXISTS public.entrega_item (
    entrega_item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entrega_id bigint NOT NULL REFERENCES public.entrega(entrega_id) ON DELETE CASCADE,
    movimento_id bigint NOT NULL REFERENCES public.movimento(movimento_id) ON DELETE CASCADE,
    empresa_id integer NOT NULL REFERENCES public.empresa(empresa_id) ON DELETE CASCADE,
    status_entrega character varying(20) DEFAULT 'Pendente'::character varying NOT NULL,
    ordem_sequencia integer DEFAULT 0 NOT NULL,
    excluido boolean DEFAULT false NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now() NOT NULL,
    dt_alteracao timestamp with time zone DEFAULT now() NOT NULL
);

-- Primary Key
ALTER TABLE ONLY public.entrega_item DROP CONSTRAINT IF EXISTS entrega_item_pkey CASCADE;
ALTER TABLE ONLY public.entrega_item ADD CONSTRAINT entrega_item_pkey PRIMARY KEY (entrega_item_id);

-- 4. Função e trigger para autogeração de cd_entrega usando a tabela sys_sequencial
CREATE OR REPLACE FUNCTION public.fn_entrega_generate_cd_entrega()
RETURNS TRIGGER AS $$
DECLARE
  v_ult_seq bigint;
BEGIN
  IF NEW.cd_entrega IS NULL OR NEW.cd_entrega = 0 THEN
    -- Realiza o upsert de forma atômica para garantir consistência e evitar concorrência
    INSERT INTO public.sys_sequencial (empresa_id, tabela, nm_campo1, nm_campo2, ult_seq)
    VALUES (NEW.empresa_id, 'entrega', 'cd_entrega', '', 1)
    ON CONFLICT (empresa_id, tabela, nm_campo1, nm_campo2)
    DO UPDATE SET ult_seq = sys_sequencial.ult_seq + 1
    RETURNING ult_seq INTO v_ult_seq;

    NEW.cd_entrega := v_ult_seq;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tg_entrega_generate_cd ON public.entrega;
CREATE TRIGGER tg_entrega_generate_cd
BEFORE INSERT ON public.entrega
FOR EACH ROW
EXECUTE FUNCTION public.fn_entrega_generate_cd_entrega();

-- 5. Configuração de Row Level Security (RLS)
ALTER TABLE public.entrega ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entrega_item ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Auth can select entrega" ON public.entrega;
CREATE POLICY "Auth can select entrega" ON public.entrega FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Auth can insert entrega" ON public.entrega;
CREATE POLICY "Auth can insert entrega" ON public.entrega FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Auth can update entrega" ON public.entrega;
CREATE POLICY "Auth can update entrega" ON public.entrega FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Auth can delete entrega" ON public.entrega;
CREATE POLICY "Auth can delete entrega" ON public.entrega FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "Auth can select entrega_item" ON public.entrega_item;
CREATE POLICY "Auth can select entrega_item" ON public.entrega_item FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Auth can insert entrega_item" ON public.entrega_item;
CREATE POLICY "Auth can insert entrega_item" ON public.entrega_item FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Auth can update entrega_item" ON public.entrega_item;
CREATE POLICY "Auth can update entrega_item" ON public.entrega_item FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Auth can delete entrega_item" ON public.entrega_item;
CREATE POLICY "Auth can delete entrega_item" ON public.entrega_item FOR DELETE TO authenticated USING (true);

-- 6. Registra a nova versão do sistema
INSERT INTO public.sistema_versoes (versao, titulo, detalhes, autor, fase, tecnologias, created_at)
VALUES (
  '1.14.0',
  'Módulo de Controle de Entregas - Banco de Dados',
  'Criação das tabelas de entrega e entrega_item, controle sequencial cd_entrega via sys_sequencial e RLS policies.',
  'Antigravity',
  'Fase 14',
  ARRAY['PostgreSQL', 'Supabase', 'Database Schema', 'Triggers'],
  now()
);
