-- Migration for Secure Virtual Store Integration
-- Naming Pattern: 20260519010000_lojavirtual_integration.sql

-- 1) Configure empresa table
ALTER TABLE public.empresa ADD COLUMN IF NOT EXISTS deposito_venda_externa_id bigint;

-- 2) Create sequence for emovimento
CREATE SEQUENCE IF NOT EXISTS public.emovimento_nr_seq START WITH 1001;

-- 3) Create secure customer table for guest store clients (standardized with cadastro)
CREATE TABLE IF NOT EXISTS public.cliente (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj text NOT NULL, -- CPF/CNPJ
  razao_social text NOT NULL, -- Nome Completo
  fone_geral text, -- Telefone
  dep_nome1 text, -- Nome do(s) filho(s)
  dt_cadastro timestamp with time zone DEFAULT now(),
  excluido boolean DEFAULT false
);

-- 4) Create secure external movement tables (prefix 'e')
CREATE TABLE IF NOT EXISTS public.emovimento (
  emovimento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  cadastro_id bigint REFERENCES public.cadastro(cadastro_id),
  cliente_id bigint REFERENCES public.cliente(id),
  nr_movimento bigint DEFAULT nextval('public.emovimento_nr_seq'),
  tp_movimento character varying(2) DEFAULT 'PD',
  tp_origem character varying(10) DEFAULT 'LINK',
  st_pedido character varying(2) DEFAULT 'A', -- 'A'=Aberto, 'R'=Reservado (Pago), 'C'=Cancelado, 'F'=Finalizado (Caixa)
  dt_emissao timestamp with time zone DEFAULT now(),
  dt_finalizacao timestamp with time zone,
  dt_cancelamento timestamp with time zone,
  vl_produto numeric(18,4) DEFAULT 0,
  vl_desconto numeric(18,4) DEFAULT 0,
  vl_movimento numeric(18,4) DEFAULT 0,
  observacao character varying(255) DEFAULT '',
  nm_responsavel text DEFAULT '',
  nr_telefone_responsavel text DEFAULT '',
  email_responsavel text DEFAULT '',
  nm_crianca text DEFAULT '',
  excluido boolean DEFAULT false,
  deposito_id bigint,
  id_transacao_abacatepay text DEFAULT '',
  url_pagamento text DEFAULT '',
  qr_code_pagamento text DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.emovimento_item (
  emovimento_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  emovimento_id bigint NOT NULL REFERENCES public.emovimento(emovimento_id) ON DELETE CASCADE,
  produto_id bigint REFERENCES public.produto(produto_id),
  cd_produto text DEFAULT '',
  nm_produto text DEFAULT '',
  unidade_id character varying(10),
  tp_movimento character varying(2) DEFAULT 'PD',
  qt_movimento numeric(18,4) DEFAULT 1,
  vl_und_produto numeric(18,4) DEFAULT 0,
  vl_produto numeric(18,4) DEFAULT 0,
  vl_desconto numeric(18,4) DEFAULT 0,
  vl_movimento numeric(18,4) DEFAULT 0,
  excluido boolean DEFAULT false,
  deposito_id bigint,
  entrega character varying(2) DEFAULT 'S', -- default 'S' para reservar estoque de entrega futura
  qt_reservada numeric(18,4) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.emovimento_pagamento (
  emovimento_pagamento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  emovimento_id bigint NOT NULL REFERENCES public.emovimento(emovimento_id) ON DELETE CASCADE,
  tp_pagamento text NOT NULL,
  vl_pagamento numeric(18,4) DEFAULT 0,
  dt_pagamento timestamp with time zone DEFAULT now(),
  nr_autorizacao text DEFAULT '',
  obs_pagamento text DEFAULT '',
  excluido boolean DEFAULT false,
  condicao_id bigint,
  n_parcelas bigint DEFAULT 1,
  vl_total numeric(18,4) DEFAULT 0
);

-- 5) Trigger functions for external movement tables calculations
CREATE OR REPLACE FUNCTION public.fn_emovimento_item_calc_before()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.vl_produto = COALESCE(NEW.qt_movimento, 0) * COALESCE(NEW.vl_und_produto, 0);
    NEW.vl_movimento = COALESCE(NEW.vl_produto, 0) - COALESCE(NEW.vl_desconto, 0);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_emovimento_item_before ON public.emovimento_item;
CREATE TRIGGER tg_emovimento_item_before
BEFORE INSERT OR UPDATE ON public.emovimento_item
FOR EACH ROW EXECUTE FUNCTION public.fn_emovimento_item_calc_before();

CREATE OR REPLACE FUNCTION public.fn_emovimento_totalize()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_emov_id BIGINT;
    v_vl_produto NUMERIC(18,4) := 0;
    v_vl_desconto NUMERIC(18,4) := 0;
    v_vl_movimento NUMERIC(18,4) := 0;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_emov_id := OLD.emovimento_id;
    ELSE
        v_emov_id := NEW.emovimento_id;
    END IF;

    IF pg_trigger_depth() > 1 THEN
        RETURN NULL;
    END IF;

    -- Sum totals from active items
    SELECT 
        COALESCE(SUM(vl_produto), 0),
        COALESCE(SUM(vl_desconto), 0),
        COALESCE(SUM(vl_movimento), 0)
    INTO 
        v_vl_produto, v_vl_desconto, v_vl_movimento
    FROM public.emovimento_item
    WHERE emovimento_id = v_emov_id AND excluido = false;

    -- Update emovimento header
    UPDATE public.emovimento
    SET 
        vl_produto = v_vl_produto,
        vl_desconto = v_vl_desconto,
        vl_movimento = v_vl_movimento
    WHERE emovimento_id = v_emov_id;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS tg_emovimento_item_after ON public.emovimento_item;
CREATE TRIGGER tg_emovimento_item_after
AFTER INSERT OR UPDATE OR DELETE ON public.emovimento_item
FOR EACH ROW EXECUTE FUNCTION public.fn_emovimento_totalize();

-- 6) Create secure storefront products view (inner join with fallback warehouse)
CREATE OR REPLACE VIEW public.vw_produtos_disponiveis AS
 SELECT p.produto_id AS id,
    p.produto_id::text AS xcd_produto,
    p.nome AS xnm_produto,
    p.preco_venda AS xvl_preco_venda,
    p.url_foto AS xurl_foto,
    pg.nome AS xnm_grupo_produto,
    COALESCE(e.estoque_disponivel, 0) AS xqt_estoque_disponivel,
    p.venda_online AS xlg_venda_online,
    p.dias_venda_online AS xdias_venda_online,
    p.excluido AS excluido_visivel
 FROM public.produto p
 LEFT JOIN public.produto_grupo pg ON pg.produto_grupo_id = p.produto_grupo_id
 LEFT JOIN public.empresa emp ON emp.empresa_id = p.empresa_id
 LEFT JOIN public.estoque e ON e.produto_id = p.produto_id 
    AND e.empresa_id = p.empresa_id 
    AND e.deposito_id = COALESCE(emp.deposito_venda_externa_id, emp.deposito_estoque_caixa, 1)
 WHERE p.excluido = false;

ALTER VIEW public.vw_produtos_disponiveis SET (security_invoker = true);

-- 7) Create union view for cashier PDV
CREATE OR REPLACE VIEW public.vw_pedidos_caixa_union AS
SELECT 
  m.movimento_id,
  m.nr_movimento,
  m.cadastro_id,
  COALESCE(c.nome_fantasia, c.razao_social, '(Consumidor)')::text AS cliente_nome,
  m.funcionario_id AS vendedor_id,
  (SELECT f.nome FROM public.funcionario f WHERE f.funcionario_id = m.funcionario_id)::text AS vendedor_nome,
  m.vl_movimento,
  m.dt_emissao,
  false AS is_external,
  'LOCAL'::text AS origem
FROM public.movimento m
LEFT JOIN public.cadastro c ON c.cadastro_id = m.cadastro_id
WHERE m.st_pedido = 'F' 
  AND m.excluido = false

UNION ALL

SELECT 
  em.emovimento_id AS movimento_id,
  em.nr_movimento,
  em.cadastro_id,
  COALESCE(cl.razao_social, '(Consumidor Virtual)')::text AS cliente_nome,
  NULL::bigint AS vendedor_id,
  'Loja Virtual'::text AS vendedor_nome,
  em.vl_movimento,
  em.dt_emissao,
  true AS is_external,
  'VIRTUAL'::text AS origem
FROM public.emovimento em
LEFT JOIN public.cliente cl ON cl.id = em.cliente_id
WHERE em.st_pedido = 'R' 
  AND em.excluido = false;

-- 8) Refactor secure public storefront RPCs (with standardized client names)
CREATE OR REPLACE FUNCTION public.fu_get_cliente_public(_cpf text)
RETURNS TABLE(
  id bigint,
  razao_social text,
  fone_geral text,
  dep_nome1 text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cpf text := regexp_replace(coalesce(_cpf, ''), '\D', '', 'g');
BEGIN
  -- First, check main system's cadastro
  RETURN QUERY
  SELECT 
    c.cadastro_id AS id, 
    c.razao_social::text AS razao_social, 
    c.fone_geral::text AS fone_geral, 
    c.dep_nome1::text AS dep_nome1
  FROM public.cadastro c
  WHERE c.excluido = false
    AND c.cnpj = v_cpf
  ORDER BY c.cadastro_id DESC
  LIMIT 1;

  -- If not found in cadastro, check the external cliente table
  IF NOT FOUND THEN
    RETURN QUERY
    SELECT 
      cl.id, 
      cl.razao_social, 
      cl.fone_geral, 
      cl.dep_nome1
    FROM public.cliente cl
    WHERE cl.xnr_cpf_cnpj = v_cpf
    ORDER BY cl.id DESC
    LIMIT 1;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.fu_upsert_cliente_public(
  _cpf text,
  _nome text,
  _telefone text,
  _filhos text
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cpf text := regexp_replace(coalesce(_cpf, ''), '\D', '', 'g');
  v_id bigint;
BEGIN
  IF length(v_cpf) < 11 THEN
    RAISE EXCEPTION 'CPF inválido';
  END IF;

  IF btrim(coalesce(_nome, '')) = '' THEN
    RAISE EXCEPTION 'Nome obrigatório';
  END IF;

  IF btrim(coalesce(_filhos, '')) = '' THEN
    RAISE EXCEPTION 'Nome do(s) filho(s) obrigatório';
  END IF;

  -- Verify in cliente table
  SELECT cl.id INTO v_id
  FROM public.cliente cl
  WHERE cl.cnpj = v_cpf
  ORDER BY cl.id DESC
  LIMIT 1;

  IF v_id IS NULL THEN
    INSERT INTO public.cliente (
      cnpj,
      razao_social,
      fone_geral,
      dep_nome1
    )
    VALUES (
      v_cpf,
      btrim(_nome),
      nullif(btrim(coalesce(_telefone, '')), ''),
      btrim(_filhos)
    )
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.cliente
       SET razao_social = btrim(_nome),
           fone_geral = nullif(btrim(coalesce(_telefone, '')), ''),
           dep_nome1 = btrim(_filhos)
     WHERE id = v_id;
  END IF;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.fu_list_pedidos_public(_cpf text)
RETURNS TABLE(
  id bigint,
  nr_movimento bigint,
  dt_emissao timestamp with time zone,
  vl_movimento numeric,
  st_pedido text,
  items jsonb
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    em.emovimento_id AS id,
    em.nr_movimento,
    em.dt_emissao,
    em.vl_movimento::numeric,
    em.st_pedido::text,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'xnm_produto', emi.nm_produto,
          'xqt_item', emi.qt_movimento,
          'xvl_unitario', emi.vl_und_produto,
          'xproduto_id', emi.produto_id
        )
        ORDER BY emi.emovimento_item_id
      ) FILTER (WHERE emi.emovimento_item_id IS NOT NULL),
      '[]'::jsonb
    ) AS items
  FROM public.emovimento em
  JOIN public.cliente cl
    ON cl.id = em.cliente_id
  LEFT JOIN public.emovimento_item emi
    ON emi.emovimento_id = em.emovimento_id
   AND emi.excluido = false
  WHERE em.excluido = false
    AND cl.cnpj = regexp_replace(coalesce(_cpf, ''), '\D', '', 'g')
  GROUP BY em.emovimento_id, em.nr_movimento, em.dt_emissao, em.vl_movimento, em.st_pedido
  ORDER BY em.dt_emissao DESC
  LIMIT 10;
$$;

CREATE OR REPLACE FUNCTION public.fu_get_pedido_status_public(
  _pedido_id bigint,
  _cpf text
)
RETURNS TABLE(
  id bigint,
  nr_movimento bigint,
  st_pedido text,
  dt_emissao timestamp with time zone,
  vl_movimento numeric,
  url_pagamento text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    em.emovimento_id AS id,
    em.nr_movimento,
    em.st_pedido::text,
    em.dt_emissao,
    em.vl_movimento::numeric,
    em.url_pagamento
  FROM public.emovimento em
  JOIN public.cliente cl
    ON cl.id = em.cliente_id
  WHERE em.emovimento_id = _pedido_id
    AND em.excluido = false
    AND cl.cnpj = regexp_replace(coalesce(_cpf, ''), '\D', '', 'g')
  LIMIT 1;
$$;

-- 9) Create secure atomic transition/checkout RPC for the cashier
CREATE OR REPLACE FUNCTION public.fu_pdv_confirmar_venda_externa(
  _emovimento_id bigint,
  _caixa_abertura_id bigint,
  _funcionario_caixa_id bigint,
  _dt_movimento date,
  _tp_operacao_caixa text,
  _centro_custo_caixa bigint,
  _usuario_id uuid DEFAULT NULL::uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_emov RECORD;
  v_cl RECORD;
  v_cadastro_id bigint;
  v_movimento_id bigint;
  v_item RECORD;
  v_pag jsonb;
  v_res jsonb;
BEGIN
  -- 1. Load emovimento
  SELECT * INTO v_emov FROM public.emovimento WHERE emovimento_id = _emovimento_id AND excluido = false;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Pedido da loja virtual não encontrado.');
  END IF;

  IF v_emov.st_pedido = 'F' THEN
    RETURN jsonb_build_object('error', 'Pedido já finalizado no caixa.');
  END IF;

  -- 2. Fetch or create client in public.cadastro
  SELECT * INTO v_cl FROM public.cliente WHERE id = v_emov.cliente_id;
  IF FOUND THEN
    SELECT cadastro_id INTO v_cadastro_id FROM public.cadastro 
    WHERE cnpj = v_cl.cnpj AND excluido = false 
    ORDER BY cadastro_id DESC LIMIT 1;

    IF v_cadastro_id IS NULL THEN
      INSERT INTO public.cadastro (
        empresa_id,
        razao_social,
        cnpj,
        fone_geral,
        dep_nome1,
        tipo_cadastro,
        st_cadastro,
        st_cliente,
        excluido,
        dt_cadastro
      ) VALUES (
        v_emov.empresa_id,
        v_cl.razao_social,
        v_cl.cnpj,
        v_cl.fone_geral,
        v_cl.dep_nome1,
        'C',
        'A',
        'S',
        false,
        now()
      ) RETURNING cadastro_id INTO v_cadastro_id;
    END IF;
  END IF;

  IF v_cadastro_id IS NULL THEN
    v_cadastro_id := v_emov.cadastro_id;
  END IF;

  -- 3. Update cadastro_id in emovimento
  UPDATE public.emovimento SET cadastro_id = v_cadastro_id WHERE emovimento_id = _emovimento_id;

  -- 4. Create internal local movement (draft status so cashier registrar can fatura)
  INSERT INTO public.movimento (
    empresa_id,
    cadastro_id,
    tp_movimento,
    st_pedido, -- 'A' so fu_pdv_registrar_recebimento_venda processes it!
    dt_emissao,
    vl_produto,
    vl_desconto,
    vl_movimento,
    vl_total_nota,
    observacao,
    excluido,
    funcionario_id
  ) VALUES (
    v_emov.empresa_id,
    v_cadastro_id,
    'PD',
    'A',
    now(),
    v_emov.vl_produto,
    v_emov.vl_desconto,
    v_emov.vl_movimento,
    v_emov.vl_movimento,
    'Importado Loja Virtual #' || v_emov.nr_movimento || ' - Resp: ' || v_emov.nm_responsavel,
    false,
    _funcionario_caixa_id
  ) RETURNING movimento_id INTO v_movimento_id;

  -- 5. Copy lines into movimento_item
  FOR v_item IN SELECT * FROM public.emovimento_item WHERE emovimento_id = _emovimento_id AND excluido = false LOOP
    INSERT INTO public.movimento_item (
      empresa_id,
      movimento_id,
      produto_id,
      cd_produto,
      nm_produto,
      unidade_id,
      tp_movimento,
      qt_movimento,
      vl_und_produto,
      vl_produto,
      vl_desconto,
      vl_movimento,
      excluido,
      deposito_id,
      entrega,
      qt_reservada
    ) VALUES (
      v_item.empresa_id,
      v_movimento_id,
      v_item.produto_id,
      v_item.cd_produto,
      v_item.nm_produto,
      v_item.unidade_id,
      v_item.tp_movimento,
      v_item.qt_movimento,
      v_item.vl_und_produto,
      v_item.vl_produto,
      v_item.vl_desconto,
      v_item.vl_movimento,
      false,
      v_item.deposito_id,
      v_item.entrega,
      v_item.qt_reservada
    );
  END LOOP;

  -- 6. Form payments JSONB (meio_pagamento_id = 17 for paid online pix)
  SELECT jsonb_agg(
    jsonb_build_object(
      'vl_recebido', ep.vl_pagamento,
      'condicao_id', COALESCE(ep.condicao_id, 1),
      'condicao_descricao', ep.tp_pagamento,
      'numero_autoriza', COALESCE(ep.nr_autorizacao, ''),
      'qt_parcela', COALESCE(ep.n_parcelas, 1),
      'meio_pagamento_id', 17, -- PIX Dinâmico (Online)
      'plano_conta_id', 1
    )
  ) INTO v_pag
  FROM public.emovimento_pagamento ep
  WHERE ep.emovimento_id = _emovimento_id AND ep.excluido = false;

  IF v_pag IS NULL OR jsonb_array_length(v_pag) = 0 THEN
    v_pag := jsonb_build_array(
      jsonb_build_object(
        'vl_recebido', v_emov.vl_movimento,
        'condicao_id', 1,
        'condicao_descricao', 'PIX ONLINE',
        'numero_autoriza', COALESCE(v_emov.id_transacao_abacatepay, ''),
        'qt_parcela', 1,
        'meio_pagamento_id', 17,
        'plano_conta_id', 1
      )
    );
  END IF;

  -- 7. Call cashier finalizer
  v_res := public.fu_pdv_registrar_recebimento_venda(
    v_emov.empresa_id,
    v_movimento_id,
    _caixa_abertura_id,
    _funcionario_caixa_id,
    _dt_movimento,
    _tp_operacao_caixa,
    _centro_custo_caixa,
    v_pag,
    _usuario_id
  );

  IF v_res->>'error' IS NOT NULL THEN
    RAISE EXCEPTION '%', v_res->>'error';
  END IF;

  -- 8. Mark virtual order as Finalized
  UPDATE public.emovimento 
  SET st_pedido = 'F',
      dt_finalizacao = now()
  WHERE emovimento_id = _emovimento_id;

  RETURN v_res;

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('error', SQLERRM);
END;
$$;

-- 10) Security Rules and Row Level Security (RLS) policies
ALTER TABLE public.cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emovimento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emovimento_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emovimento_pagamento ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public storefront guest insertion" ON public.cliente;
DROP POLICY IF EXISTS "Public storefront guest selection" ON public.cliente;
DROP POLICY IF EXISTS "Public storefront emovimento insertion" ON public.emovimento;
DROP POLICY IF EXISTS "Public storefront emovimento selection" ON public.emovimento;
DROP POLICY IF EXISTS "Public storefront emovimento update" ON public.emovimento;
DROP POLICY IF EXISTS "Public storefront emovimento_item insertion" ON public.emovimento_item;
DROP POLICY IF EXISTS "Public storefront emovimento_item selection" ON public.emovimento_item;
DROP POLICY IF EXISTS "Public storefront emovimento_pagamento insertion" ON public.emovimento_pagamento;
DROP POLICY IF EXISTS "Public storefront emovimento_pagamento selection" ON public.emovimento_pagamento;
DROP POLICY IF EXISTS "Authenticated staff full access client" ON public.cliente;
DROP POLICY IF EXISTS "Authenticated staff full access emov" ON public.emovimento;
DROP POLICY IF EXISTS "Authenticated staff full access emov_item" ON public.emovimento_item;
DROP POLICY IF EXISTS "Authenticated staff full access emov_pag" ON public.emovimento_pagamento;

-- Guest storefront access (INSERT + minimal select)
CREATE POLICY "Public storefront guest insertion" ON public.cliente FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public storefront guest selection" ON public.cliente FOR SELECT TO anon USING (true);

CREATE POLICY "Public storefront emovimento insertion" ON public.emovimento FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public storefront emovimento selection" ON public.emovimento FOR SELECT TO anon USING (true);
CREATE POLICY "Public storefront emovimento update" ON public.emovimento FOR UPDATE TO anon USING (true);

CREATE POLICY "Public storefront emovimento_item insertion" ON public.emovimento_item FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public storefront emovimento_item selection" ON public.emovimento_item FOR SELECT TO anon USING (true);

CREATE POLICY "Public storefront emovimento_pagamento insertion" ON public.emovimento_pagamento FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public storefront emovimento_pagamento selection" ON public.emovimento_pagamento FOR SELECT TO anon USING (true);

-- Staff authenticated access (full privileges)
CREATE POLICY "Authenticated staff full access client" ON public.cliente TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated staff full access emov" ON public.emovimento TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated staff full access emov_item" ON public.emovimento_item TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated staff full access emov_pag" ON public.emovimento_pagamento TO authenticated USING (true) WITH CHECK (true);

-- 11) Grant permissions
GRANT EXECUTE ON FUNCTION public.fu_get_cliente_public(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fu_upsert_cliente_public(text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fu_list_pedidos_public(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fu_get_pedido_status_public(bigint, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fu_pdv_confirmar_venda_externa(bigint, bigint, bigint, date, text, bigint, uuid) TO authenticated;
