
-- ================================================
-- PRODUTO_FORNECEDOR
-- Vínculo entre produto interno e código do fornecedor
-- ================================================
CREATE TABLE public.PRODUTO_FORNECEDOR (
  PRODUTO_FORNECEDOR_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID             BIGINT NOT NULL,
  PRODUTO_ID             BIGINT NOT NULL REFERENCES public.produto(produto_id) ON DELETE CASCADE,
  CADASTRO_ID            BIGINT NOT NULL REFERENCES public.cadastro(cadastro_id),
  CD_PROD_FORNEC         TEXT NOT NULL DEFAULT '',
  NM_PROD_FORNEC         TEXT NOT NULL DEFAULT '',
  EXCLUIDO               BOOLEAN NOT NULL DEFAULT FALSE,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PRODUTO_FORNECEDOR
  ON public.PRODUTO_FORNECEDOR (EMPRESA_ID, CADASTRO_ID, CD_PROD_FORNEC)
  WHERE EXCLUIDO = FALSE;

CREATE INDEX IX_PRODUTO_FORNECEDOR_PRODUTO   ON public.PRODUTO_FORNECEDOR (PRODUTO_ID);
CREATE INDEX IX_PRODUTO_FORNECEDOR_CADASTRO  ON public.PRODUTO_FORNECEDOR (CADASTRO_ID);
CREATE INDEX IX_PRODUTO_FORNECEDOR_EMPRESA   ON public.PRODUTO_FORNECEDOR (EMPRESA_ID);

ALTER TABLE public.PRODUTO_FORNECEDOR ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PRODUTO_FORNECEDOR"
  ON public.PRODUTO_FORNECEDOR FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert PRODUTO_FORNECEDOR"
  ON public.PRODUTO_FORNECEDOR FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update PRODUTO_FORNECEDOR"
  ON public.PRODUTO_FORNECEDOR FOR UPDATE TO authenticated USING (true);

CREATE TRIGGER TR_PRODUTO_FORNECEDOR_UPDATED_AT
  BEFORE UPDATE ON public.PRODUTO_FORNECEDOR
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();
