
-- PART 2: REMAINING TABLES

-- CFOP
CREATE TABLE IF NOT EXISTS public.cfop (
    cfop_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo character varying(10) NOT NULL,
    descricao text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- CLIENTE_OLD
CREATE TABLE IF NOT EXISTS public.cliente_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xcd_cliente text NOT NULL,
    xnr_cpf_cnpj text DEFAULT '' NOT NULL,
    xnm_razao_social text NOT NULL,
    xnm_fantasia_social text DEFAULT '' NOT NULL,
    xnr_telefone text DEFAULT '' NOT NULL,
    xnm_crianca text DEFAULT '' NOT NULL,
    xdt_cadastro timestamp with time zone DEFAULT now(),
    xdt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false
);

-- COMISSAO
CREATE TABLE IF NOT EXISTS public.comissao (
    comissao_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cadastro_id integer,
    tp_comissao character varying(1) DEFAULT 'P',
    pc_comis_av numeric(10,2) DEFAULT 0,
    pc_comis_pr numeric(10,2) DEFAULT 0,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- CONDICAO_PAGAMENTO
CREATE TABLE IF NOT EXISTS public.condicao_pagamento (
    condicao_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    tp_doc character varying(20) DEFAULT '' NOT NULL,
    prazo_1 integer DEFAULT 0,
    prazo_2 integer DEFAULT 0 NOT NULL,
    prazo_3 integer DEFAULT 0 NOT NULL,
    prazo_4 integer DEFAULT 0 NOT NULL,
    prazo_5 integer DEFAULT 0 NOT NULL,
    prazo_6 integer DEFAULT 0 NOT NULL,
    prazo_7 integer DEFAULT 0 NOT NULL,
    prazo_8 integer DEFAULT 0 NOT NULL,
    prazo_9 integer DEFAULT 0 NOT NULL,
    prazo_10 integer DEFAULT 0 NOT NULL,
    prazo_11 integer DEFAULT 0 NOT NULL,
    prazo_12 integer DEFAULT 0 NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- CORRETORA
CREATE TABLE IF NOT EXISTS public.corretora (
    corretora_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- DEPOSITO
CREATE TABLE IF NOT EXISTS public.deposito (
    deposito_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    nome character varying NOT NULL,
    endereco character varying DEFAULT '' NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false
);

-- ESTOQUE
CREATE TABLE IF NOT EXISTS public.estoque (
    estoque_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    deposito_id integer DEFAULT 1 NOT NULL,
    produto_id bigint NOT NULL,
    estoque_fisico numeric(18,4) DEFAULT 0,
    estoque_reservado numeric(18,4) DEFAULT 0,
    estoque_disponivel numeric(18,4) GENERATED ALWAYS AS ((estoque_fisico - estoque_reservado)) STORED,
    estoque_minimo numeric(18,4) DEFAULT 0,
    estoque_padrao numeric(18,4) DEFAULT 0,
    estoque_inventario numeric(18,4) DEFAULT 0,
    dt_alteracao timestamp with time zone DEFAULT now(),
    dt_ult_saida timestamp with time zone,
    dt_ult_entrada timestamp with time zone,
    excluido boolean DEFAULT false
);

-- FINANCEIRO
CREATE TABLE IF NOT EXISTS public.financeiro (
    financeiro_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    tp_financeiro character varying(1) DEFAULT 'R' NOT NULL,
    nr_documento character varying(50) DEFAULT '' NOT NULL,
    nr_parcela integer DEFAULT 1,
    cadastro_id bigint,
    movimento_id bigint,
    dt_emissao timestamp with time zone DEFAULT now(),
    dt_vencimento timestamp with time zone NOT NULL,
    dt_pagamento timestamp with time zone,
    dt_cancelamento timestamp with time zone,
    vl_documento numeric(15,2) DEFAULT 0 NOT NULL,
    vl_pago numeric(15,2) DEFAULT 0,
    vl_desconto numeric(15,2) DEFAULT 0,
    vl_juros numeric(15,2) DEFAULT 0,
    vl_multa numeric(15,2) DEFAULT 0,
    vl_saldo numeric(15,2) DEFAULT 0,
    st_financeiro character varying(1) DEFAULT 'A',
    tp_pagamento character varying(30) DEFAULT '' NOT NULL,
    observacao text DEFAULT '' NOT NULL,
    plano_conta_id integer,
    portador_id integer,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now()
);

-- FINANCEIRO_BAIXA
CREATE TABLE IF NOT EXISTS public.financeiro_baixa (
    financeiro_baixa_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    financeiro_id bigint NOT NULL,
    empresa_id bigint DEFAULT 1 NOT NULL,
    dt_baixa timestamp with time zone DEFAULT now(),
    vl_baixa numeric(15,2) DEFAULT 0 NOT NULL,
    vl_desconto numeric(15,2) DEFAULT 0,
    vl_juros numeric(15,2) DEFAULT 0,
    vl_multa numeric(15,2) DEFAULT 0,
    tp_pagamento character varying(30) DEFAULT '' NOT NULL,
    nr_autorizacao character varying(50) DEFAULT '' NOT NULL,
    observacao text DEFAULT '' NOT NULL,
    usuario_id uuid,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now()
);

-- GRUPO_ICMS
CREATE TABLE IF NOT EXISTS public.grupo_icms (
    grupo_icms_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- GRUPO_IPI
CREATE TABLE IF NOT EXISTS public.grupo_ipi (
    grupo_ipi_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- GRUPO_PIS_COFINS
CREATE TABLE IF NOT EXISTS public.grupo_pis_cofins (
    grupo_pis_cofins_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- GRUPO_PRODUTO_OLD
CREATE TABLE IF NOT EXISTS public.grupo_produto_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xcd_grupo_produto text NOT NULL,
    xnm_grupo_produto text NOT NULL,
    xdt_cadastro timestamp with time zone DEFAULT now(),
    xdt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false
);

-- LINHA_PRODUTO
CREATE TABLE IF NOT EXISTS public.linha_produto (
    linha_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- MOVIMENTO (need sequence first)
CREATE SEQUENCE IF NOT EXISTS public.movimento_nr_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS public.movimento (
    movimento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    tp_movimento character varying(2) DEFAULT 'PD',
    nr_movimento bigint DEFAULT nextval('public.movimento_nr_seq'),
    cadastro_id bigint,
    dt_emissao timestamp with time zone DEFAULT now(),
    hr_movimento text DEFAULT '' NOT NULL,
    vl_produto numeric(12,2) DEFAULT 0,
    vl_desconto numeric(12,2) DEFAULT 0,
    vl_movimento numeric(12,2) DEFAULT 0,
    st_pedido character varying(1) DEFAULT 'A',
    status character varying(1) DEFAULT 'A',
    faturado character varying(1) DEFAULT 'N',
    observacao character varying(300) DEFAULT '' NOT NULL,
    tp_origem character varying(10) DEFAULT 'PDV',
    lg_pedido_link boolean DEFAULT false,
    lg_pedido_pdv boolean DEFAULT false,
    lg_pagamento_online boolean DEFAULT false,
    dt_pagamento timestamp with time zone,
    dt_finalizacao timestamp with time zone,
    dt_faturamento timestamp with time zone,
    dt_cancelamento timestamp with time zone,
    usuario_id uuid,
    nm_responsavel text DEFAULT '' NOT NULL,
    nr_telefone_responsavel text DEFAULT '' NOT NULL,
    email_responsavel text DEFAULT '' NOT NULL,
    nm_crianca text DEFAULT '' NOT NULL,
    obs_pedido text DEFAULT '' NOT NULL,
    id_transacao_abacatepay text DEFAULT '' NOT NULL,
    url_pagamento text DEFAULT '' NOT NULL,
    qr_code_pagamento text DEFAULT '' NOT NULL,
    excluido boolean DEFAULT false
);

-- MOVIMENTO_ITEM
CREATE TABLE IF NOT EXISTS public.movimento_item (
    movimento_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    movimento_id bigint NOT NULL,
    produto_id bigint,
    tp_movimento character varying(2) DEFAULT 'PD',
    qt_movimento numeric(14,4) DEFAULT 1,
    vl_und_produto numeric(18,8) DEFAULT 0,
    vl_produto numeric(12,2) DEFAULT 0,
    vl_desconto numeric(12,2) DEFAULT 0,
    vl_movimento numeric(12,2) DEFAULT 0,
    unidade_id character varying(5),
    nm_produto text DEFAULT '' NOT NULL,
    cd_produto text DEFAULT '' NOT NULL,
    excluido boolean DEFAULT false
);

-- MOVIMENTO_PAGAMENTO
CREATE TABLE IF NOT EXISTS public.movimento_pagamento (
    movimento_pagamento_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    movimento_id bigint NOT NULL,
    tp_pagamento text NOT NULL,
    vl_pagamento numeric(12,2) DEFAULT 0,
    dt_pagamento timestamp with time zone DEFAULT now(),
    nr_autorizacao text DEFAULT '' NOT NULL,
    obs_pagamento text DEFAULT '' NOT NULL,
    excluido boolean DEFAULT false
);

-- PARAMETRO
CREATE TABLE IF NOT EXISTS public.parametro (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xnm_escola text DEFAULT 'Escola',
    xurl_logo text DEFAULT '' NOT NULL,
    xurl_favicon text DEFAULT '' NOT NULL,
    xurl_banner_vendas text DEFAULT '' NOT NULL,
    xurl_link_vendas text DEFAULT '' NOT NULL,
    xlg_valida_estoque_link boolean DEFAULT true,
    xlg_valida_estoque_pdv boolean DEFAULT false,
    xmsg_pos_pagamento text DEFAULT 'Pagamento confirmado! Seu lanche estará disponível para retirada.',
    xemail_remetente text DEFAULT '' NOT NULL,
    xabacatepay_api_key text DEFAULT '' NOT NULL,
    xabacatepay_webhook_url text DEFAULT '' NOT NULL,
    xcor_primaria text DEFAULT '#8B5CF6',
    xcor_secundaria text DEFAULT '#6D28D9',
    xcor_destaque text DEFAULT '#F59E0B',
    xcor_fundo text DEFAULT '#FFFFFF',
    xcor_fundo_card text DEFAULT '#F8FAFC',
    xcor_texto_principal text DEFAULT '#1E293B',
    xcor_texto_secundario text DEFAULT '#64748B',
    xcor_botao text DEFAULT '#8B5CF6',
    xcor_botao_negativo text DEFAULT '#EF4444',
    xcor_header text DEFAULT '#7C3AED',
    xcor_menu text DEFAULT '#4C1D95',
    xcor_link text DEFAULT '#8B5CF6',
    xcss_customizado text DEFAULT '' NOT NULL,
    xdt_cadastro timestamp with time zone DEFAULT now(),
    xdt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false,
    xabacatepay_webhook_secret text DEFAULT '' NOT NULL
);

-- PARAMETRO_HORARIO
CREATE TABLE IF NOT EXISTS public.parametro_horario (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xparametro_id bigint,
    xdia_semana integer NOT NULL,
    xhr_inicio_matutino time without time zone,
    xhr_fim_matutino time without time zone,
    xhr_inicio_vespertino time without time zone,
    xhr_fim_vespertino time without time zone,
    xlg_dia_ativo boolean DEFAULT false,
    excluido boolean DEFAULT false
);

-- PEDIDO_OLD (need sequence first)
CREATE SEQUENCE IF NOT EXISTS public.pedido_nr_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS public.pedido_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xnr_pedido bigint DEFAULT nextval('public.pedido_nr_seq'),
    xcliente_id bigint,
    xtipo_origem_pedido text DEFAULT 'PDV',
    xst_pedido text DEFAULT 'A',
    xdt_pedido timestamp with time zone DEFAULT now(),
    xhr_pedido text DEFAULT '' NOT NULL,
    xvl_total_bruto numeric(15,2) DEFAULT 0,
    xvl_total_desconto numeric(15,2) DEFAULT 0,
    xvl_total_liquido numeric(15,2) DEFAULT 0,
    xnm_responsavel text DEFAULT '' NOT NULL,
    xnr_telefone_responsavel text DEFAULT '' NOT NULL,
    xemail_responsavel text DEFAULT '' NOT NULL,
    xnm_crianca text DEFAULT '' NOT NULL,
    xlg_pedido_link boolean DEFAULT false,
    xlg_pedido_pdv boolean DEFAULT false,
    xlg_pagamento_online boolean DEFAULT false,
    xobs_pedido text DEFAULT '' NOT NULL,
    xid_transacao_abacatepay text DEFAULT '' NOT NULL,
    xurl_pagamento text DEFAULT '' NOT NULL,
    xqr_code_pagamento text DEFAULT '' NOT NULL,
    xdt_pagamento timestamp with time zone,
    xdt_finalizacao timestamp with time zone,
    xdt_faturamento timestamp with time zone,
    xdt_cancelamento timestamp with time zone,
    xusuario_id uuid,
    excluido boolean DEFAULT false
);

-- PEDIDO_ITEM_OLD
CREATE TABLE IF NOT EXISTS public.pedido_item_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xpedido_id bigint NOT NULL,
    xproduto_id bigint,
    xcd_produto text DEFAULT '' NOT NULL,
    xnm_produto text DEFAULT '' NOT NULL,
    xun_produto text DEFAULT '' NOT NULL,
    xqt_item numeric(15,3) DEFAULT 1,
    xvl_unitario numeric(15,2) DEFAULT 0,
    xvl_total_item numeric(15,2) GENERATED ALWAYS AS ((xqt_item * xvl_unitario)) STORED,
    excluido boolean DEFAULT false
);

-- PEDIDO_PAGAMENTO_OLD
CREATE TABLE IF NOT EXISTS public.pedido_pagamento_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xpedido_id bigint NOT NULL,
    xtp_pagamento text NOT NULL,
    xvl_pagamento numeric(15,2) DEFAULT 0,
    xnr_autorizacao text DEFAULT '' NOT NULL,
    xobs_pagamento text DEFAULT '' NOT NULL,
    xdt_pagamento timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false
);

-- PLANO_CONTA
CREATE TABLE IF NOT EXISTS public.plano_conta (
    plano_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta text NOT NULL,
    nome text NOT NULL,
    tp_conta character varying(1) DEFAULT 'A',
    tp_natureza character varying(1) DEFAULT 'D',
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- PORTADOR
CREATE TABLE IF NOT EXISTS public.portador (
    portador_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    banco_id integer,
    conta_id text,
    caminho_remessa text DEFAULT '' NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- PRODUTO_OLD
CREATE TABLE IF NOT EXISTS public.produto_old (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    empresa_id integer DEFAULT 1,
    xcd_produto text NOT NULL,
    xcd_barra text DEFAULT '' NOT NULL,
    xnm_produto text NOT NULL,
    xun_produto text DEFAULT 'UN',
    xurl_foto text DEFAULT '' NOT NULL,
    xgrupo_produto_id bigint,
    xqt_estoque_fisico numeric(15,3) DEFAULT 0,
    xqt_estoque_reservado numeric(15,3) DEFAULT 0,
    xqt_estoque_disponivel numeric(15,3) GENERATED ALWAYS AS ((xqt_estoque_fisico - xqt_estoque_reservado)) STORED,
    xqt_estoque_minimo numeric(15,3) DEFAULT 0,
    xqt_estoque_padrao numeric(15,3) DEFAULT 0,
    xvl_preco_compra numeric(15,2) DEFAULT 0,
    xpc_markup numeric(7,2) DEFAULT 0,
    xvl_preco_sugerido numeric(15,2) DEFAULT 0,
    xvl_preco_venda numeric(15,2) DEFAULT 0,
    xlg_venda_online boolean DEFAULT true,
    xdt_cadastro timestamp with time zone DEFAULT now(),
    xdt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false,
    xdias_venda_online text DEFAULT '0,1,2,3,4'
);

-- ROTA
CREATE TABLE IF NOT EXISTS public.rota (
    rota_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    cadastro_id integer,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- SUBGRUPO_PRODUTO
CREATE TABLE IF NOT EXISTS public.subgrupo_produto (
    subgrupo_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    grupo_id integer,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TABELA_PRECO
CREATE TABLE IF NOT EXISTS public.tabela_preco (
    tabela_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    ativo boolean DEFAULT true,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TIPO_CADASTRO
CREATE TABLE IF NOT EXISTS public.tipo_cadastro (
    tp_cadastro_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TIPO_OPERACAO
CREATE TABLE IF NOT EXISTS public.tipo_operacao (
    tipo_operacao_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    tipo_movimento character varying(1) DEFAULT 'S',
    gera_financeiro boolean DEFAULT false,
    gera_nf boolean DEFAULT false,
    gera_boleto boolean DEFAULT false,
    modifica_estoque boolean DEFAULT false,
    valida_preco boolean DEFAULT false,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TIPO_PAG_REC
CREATE TABLE IF NOT EXISTS public.tipo_pag_rec (
    tipo_pag_rec_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    tipo character varying(1) DEFAULT 'A',
    ativo boolean DEFAULT true,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- UNIDADE
CREATE TABLE IF NOT EXISTS public.unidade (
    unidade_id character varying(5) PRIMARY KEY,
    descricao text NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- VEICULO
CREATE TABLE IF NOT EXISTS public.veiculo (
    veiculo_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa character varying(10) DEFAULT '' NOT NULL,
    descricao text NOT NULL,
    marca text DEFAULT '' NOT NULL,
    modelo text DEFAULT '' NOT NULL,
    cadastro_id integer,
    ativo boolean DEFAULT true,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);
