-- Migration: 20260918201500_add_func_discount_and_create_cargo.sql
-- Descrição: Adiciona colunas pc_desc_maximo_gerente e pc_desc_maximo_vendedor na tabela funcionario e cria a tabela cargo.

-- 1. Alterar tabela funcionario
ALTER TABLE public.funcionario
  ADD COLUMN IF NOT EXISTS pc_desc_maximo_gerente numeric(15,2) DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS pc_desc_maximo_vendedor numeric(15,2) DEFAULT 0 NOT NULL;

UPDATE public.funcionario
SET pc_desc_maximo_gerente = 0
WHERE pc_desc_maximo_gerente IS NULL;

UPDATE public.funcionario
SET pc_desc_maximo_vendedor = 0
WHERE pc_desc_maximo_vendedor IS NULL;

-- 2. Criar tabela cargo
CREATE TABLE IF NOT EXISTS public.cargo (
    cargo_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_empresa_id integer DEFAULT 1 NOT NULL,
    cargo_descricao text NOT NULL,
    excluido boolean DEFAULT false NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- Habilita RLS na tabela cargo
ALTER TABLE public.cargo ENABLE ROW LEVEL SECURITY;

-- Permissões de RLS
DROP POLICY IF EXISTS "Enable all access for authenticated users on cargo" ON public.cargo;
CREATE POLICY "Enable all access for authenticated users on cargo" ON public.cargo FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.cargo TO anon;
GRANT ALL ON TABLE public.cargo TO authenticated;
GRANT ALL ON TABLE public.cargo TO service_role;
