
-- TABELA DE REGRAS FISCAIS (HEADER)
CREATE TABLE IF NOT EXISTS public.fiscal_regra (
    fiscal_regra_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    cfop_id integer REFERENCES public.cfop(cfop_id),
    observacao text,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TABELA DE IMPOSTOS DA REGRA (DETALHE)
CREATE TABLE IF NOT EXISTS public.fiscal_regra_imposto (
    fiscal_regra_imposto_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_regra_id integer REFERENCES public.fiscal_regra(fiscal_regra_id) ON DELETE CASCADE,
    tipo_imposto character varying(10) NOT NULL, -- 'ICMS', 'IPI', 'PIS', 'COFINS', 'IBS', 'CBS'
    
    -- Campos Gerais
    cst_csosn character varying(3), -- Suporta CST (Regime Normal) ou CSOSN (Simples)
    aliquota numeric(10,4) DEFAULT 0,
    base_reducao numeric(10,4) DEFAULT 0, 
    motivo_desoneracao integer,
    
    -- Específicos para Simples Nacional / Crédito
    p_cre_sn numeric(10,4) DEFAULT 0, -- Alíquota de crédito Simples Nacional (pCredSN)
    
    -- Campos específicos de ICMS
    icms_st_aliquota numeric(10,4) DEFAULT 0,
    icms_st_mva numeric(10,4) DEFAULT 0,
    icms_st_base_reducao numeric(10,4) DEFAULT 0,
    mod_bc integer DEFAULT 3, -- 0-Margem Valor Agregado; 1-Pauta; 2-Preço Tabelado Máx.; 3-Valor da Operação
    mod_bc_st integer DEFAULT 4,
    
    -- Campos específicos de IPI
    ipi_c_enq character varying(3) DEFAULT '999',
    
    empresa_id integer DEFAULT 1 NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- TABELA DE CONFIGURAÇÃO / VÍNCULO (MOTOR DE BUSCA)
CREATE TABLE IF NOT EXISTS public.fiscal_configuracao (
    fiscal_configuracao_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_operacao_id integer REFERENCES public.tipo_operacao(tipo_operacao_id),
    fiscal_regra_id integer REFERENCES public.fiscal_regra(fiscal_regra_id),
    
    -- FILTROS DE EMPRESA E OPERAÇÃO
    crt_empresa integer,                       -- 1-Simples; 2-Simples Excesso; 3-Regime Normal
    uf_origem character varying(2) DEFAULT '*',
    uf_destino character varying(2) DEFAULT '*',
    
    -- FILTROS DE CLIENTE
    cliente_contribuinte boolean,              -- true: Contribuinte; false: Não Contribuinte
    cliente_consumidor_final boolean,          -- true: Consumidor Final; false: Revenda
    cliente_beneficio_fiscal boolean DEFAULT false,
    
    -- FILTROS DE PRODUTO
    ncm character varying(10),
    grupo_icms_id integer,
    produto_tipo_tributacao character varying(20), -- 'TRIBUTADO', 'NAO_TRIBUTADO', 'REDUCAO', 'ST'
    
    cfop_id integer REFERENCES public.cfop(cfop_id), -- CFOP Resultante
    
    prioridade integer DEFAULT 0,
    
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- Adicionar CFOP padrão ao Tipo de Operação
ALTER TABLE public.tipo_operacao ADD COLUMN IF NOT EXISTS cfop_id integer REFERENCES public.cfop(cfop_id);

-- Habilitar RLS
ALTER TABLE public.fiscal_regra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fiscal_regra_imposto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fiscal_configuracao ENABLE ROW LEVEL SECURITY;

-- Políticas (Authenticated)
CREATE POLICY "Enable all for authenticated users" ON public.fiscal_regra FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.fiscal_regra_imposto FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.fiscal_configuracao FOR ALL TO authenticated USING (true);

-- Comentários
COMMENT ON COLUMN public.fiscal_configuracao.crt_empresa IS 'CRT da Empresa: 1-Simples Nacional, 2-Simples Nacional (Excesso), 3-Regime Normal';
COMMENT ON COLUMN public.fiscal_configuracao.produto_tipo_tributacao IS 'TIPO: TRIBUTADO, NAO_TRIBUTADO, REDUCAO, ST';
