
-- RB_CONEXAO: Supabase connection configurations
CREATE TABLE public.rb_conexao (
  rb_conexao_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  nome text NOT NULL,
  url text NOT NULL DEFAULT '',
  api_key text NOT NULL DEFAULT '',
  descricao text NOT NULL DEFAULT '',
  excluido boolean DEFAULT false,
  dt_cadastro timestamptz DEFAULT now(),
  dt_alteracao timestamptz DEFAULT now()
);

ALTER TABLE public.rb_conexao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rb_conexao_auth" ON public.rb_conexao FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- RB_TEMPLATEPESQUISA: reusable filter variable definitions
CREATE TABLE public.rb_templatepesquisa (
  rb_templatepesquisa_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  nome text NOT NULL,
  label text NOT NULL DEFAULT '',
  tipo text NOT NULL DEFAULT 'text',
  obrigatorio boolean DEFAULT false,
  valor_padrao text DEFAULT '',
  opcoes_fixas text DEFAULT '',
  query text DEFAULT '',
  rb_conexao_id bigint REFERENCES public.rb_conexao(rb_conexao_id),
  excluido boolean DEFAULT false,
  dt_cadastro timestamptz DEFAULT now(),
  dt_alteracao timestamptz DEFAULT now()
);

ALTER TABLE public.rb_templatepesquisa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rb_templatepesquisa_auth" ON public.rb_templatepesquisa FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- RB_RELATORIO: report definitions
CREATE TABLE public.rb_relatorio (
  rb_relatorio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL DEFAULT 1,
  nome text NOT NULL,
  rb_conexao_id bigint REFERENCES public.rb_conexao(rb_conexao_id),
  menu text NOT NULL DEFAULT '',
  submenu text NOT NULL DEFAULT '',
  ordem integer DEFAULT 0,
  query_sql text NOT NULL DEFAULT '',
  report_json jsonb,
  excluido boolean DEFAULT false,
  dt_cadastro timestamptz DEFAULT now(),
  dt_alteracao timestamptz DEFAULT now()
);

ALTER TABLE public.rb_relatorio ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rb_relatorio_auth" ON public.rb_relatorio FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- RB_RELATORIO_VARIAVEL: link report to filter variables
CREATE TABLE public.rb_relatorio_variavel (
  rb_relatorio_variavel_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rb_relatorio_id bigint NOT NULL REFERENCES public.rb_relatorio(rb_relatorio_id),
  rb_templatepesquisa_id bigint NOT NULL REFERENCES public.rb_templatepesquisa(rb_templatepesquisa_id),
  operador text NOT NULL DEFAULT '=',
  excluido boolean DEFAULT false
);

ALTER TABLE public.rb_relatorio_variavel ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rb_relatorio_variavel_auth" ON public.rb_relatorio_variavel FOR ALL TO authenticated USING (true) WITH CHECK (true);
