-- ============================================================
-- CONSOLIDAÇÃO DE GRUPOS TRIBUTÁRIOS EM UMA ÚNICA TABELA
-- ============================================================

-- 1. Criação da nova tabela unificada
CREATE TABLE IF NOT EXISTS public.fiscal_grupo_produto (
    fiscal_grupo_produto_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id              integer NOT NULL DEFAULT 1,
    nome                    varchar(30) NOT NULL,
    tp_imposto              varchar(20) NOT NULL, -- ICMS, PIS/COFINS, IBS/CBS, IPI
    excluido                boolean DEFAULT false,
    dt_cadastro             timestamptz DEFAULT now(),
    dt_alteracao            timestamptz
);

-- RLS + Policies
ALTER TABLE public.fiscal_grupo_produto ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fiscal_grupo_produto_all ON public.fiscal_grupo_produto;
CREATE POLICY fiscal_grupo_produto_all ON public.fiscal_grupo_produto
    AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON public.fiscal_grupo_produto TO authenticated, service_role;

-- 2. Migração de dados existentes
DO $$ 
BEGIN
    -- ICMS
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'grupo_icms') THEN
        INSERT INTO public.fiscal_grupo_produto (fiscal_grupo_produto_id, empresa_id, nome, tp_imposto, dt_cadastro)
        SELECT grupo_icms_id, empresa_id, substring(descricao, 1, 30), 'ICMS', dt_cadastro
        FROM public.grupo_icms ON CONFLICT DO NOTHING;
    END IF;

    -- IPI
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'grupo_ipi') THEN
        INSERT INTO public.fiscal_grupo_produto (fiscal_grupo_produto_id, empresa_id, nome, tp_imposto, dt_cadastro)
        SELECT grupo_ipi_id + 10000, empresa_id, substring(descricao, 1, 30), 'IPI', dt_cadastro
        FROM public.grupo_ipi ON CONFLICT DO NOTHING;
    END IF;

    -- PIS/COFINS
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'grupo_pis_cofins') THEN
        INSERT INTO public.fiscal_grupo_produto (fiscal_grupo_produto_id, empresa_id, nome, tp_imposto, dt_cadastro)
        SELECT grupo_pis_cofins_id + 20000, empresa_id, substring(descricao, 1, 30), 'PIS/COFINS', dt_cadastro
        FROM public.grupo_pis_cofins ON CONFLICT DO NOTHING;
    END IF;

    -- IBS/CBS
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'grupo_ibscbs') THEN
        INSERT INTO public.fiscal_grupo_produto (fiscal_grupo_produto_id, empresa_id, nome, tp_imposto, dt_cadastro)
        SELECT grupo_ibscbs_id + 30000, empresa_id, substring(descricao, 1, 30), 'IBS/CBS', dt_cadastro
        FROM public.grupo_ibscbs ON CONFLICT DO NOTHING;
    END IF;
END $$;

-- 3. Atualização das tabelas que utilizam estes grupos
-- Produto
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'produto' AND column_name = 'grupo_ipi_id') THEN
        UPDATE public.produto SET grupo_ipi_id = grupo_ipi_id + 10000 WHERE grupo_ipi_id IS NOT NULL;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'produto' AND column_name = 'grupo_pis_cofins_id') THEN
        UPDATE public.produto SET grupo_pis_cofins_id = grupo_pis_cofins_id + 20000 WHERE grupo_pis_cofins_id IS NOT NULL;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'produto' AND column_name = 'grupo_ibscbs_id') THEN
        UPDATE public.produto SET grupo_ibscbs_id = grupo_ibscbs_id + 30000 WHERE grupo_ibscbs_id IS NOT NULL;
    END IF;
END $$;

-- Fiscal Regra Item
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'fiscal_regra_item' AND column_name = 'grupo_icms_id') THEN
        UPDATE public.fiscal_regra_item SET grupo_icms_id = grupo_icms_id WHERE tipo_imposto = 'ICMS' AND grupo_icms_id IS NOT NULL;
        -- Se houvesse outros mapeamentos aqui, teríamos que fazer o mesmo shift (+10000 etc)
    END IF;
END $$;

-- 4. Remoção das tabelas antigas (DROP)
DROP TABLE IF EXISTS public.grupo_icms CASCADE;
DROP TABLE IF EXISTS public.grupo_ipi CASCADE;
DROP TABLE IF EXISTS public.grupo_pis_cofins CASCADE;
DROP TABLE IF EXISTS public.grupo_ibscbs CASCADE;
