
DROP VIEW IF EXISTS public.financeiro_view;

ALTER TABLE public.financeiro_baixa ALTER COLUMN financeiro_id DROP DEFAULT;
ALTER TABLE public.financeiro_baixa ALTER COLUMN financeiro_id TYPE bigint USING NULLIF(financeiro_id,'')::bigint;

ALTER TABLE public.boleto ALTER COLUMN financeiro_id DROP DEFAULT;
ALTER TABLE public.boleto ALTER COLUMN financeiro_id TYPE bigint USING NULLIF(financeiro_id,'')::bigint;

ALTER TABLE public.financeiro ALTER COLUMN financeiro_id DROP DEFAULT;
ALTER TABLE public.financeiro ALTER COLUMN financeiro_id TYPE bigint USING NULLIF(financeiro_id,'')::bigint;

ALTER TABLE public.financeiro ALTER COLUMN financeiro_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
  pg_get_serial_sequence('public.financeiro','financeiro_id'),
  GREATEST(COALESCE((SELECT MAX(financeiro_id) FROM public.financeiro), 1), 1)
);

CREATE OR REPLACE VIEW public.financeiro_view AS
SELECT empresa_id, financeiro_id, movimento_id, documento, parcela, tp_documento_id, tp_conta,
    dt_emissao, dt_vencto, portador_id, cadastro_id, observacao1, observacao2, vl_titulo,
    vl_desconto, vl_pago, vl_adicional, vl_despesa, linha_digitavel, cod_barras, nosso_numero,
    enviado_remissa, emitido_bol, planoconta_id, plano_id, funcionario_id, st_programacao,
    st_execucao, cadastro_id_dest, aviario, modelo, serie, quantidade, autenticacao,
    cobranca_asaas, gerou_cobranca, ativo, pct_juros, pct_multa, aplica_juros, aplica_multa, status,
    CASE WHEN vl_pago < vl_titulo AND ativo::text = 'S' AND dt_vencto IS NOT NULL
         THEN GREATEST(0, CURRENT_DATE - dt_vencto::date) ELSE 0 END AS dias_atraso,
    CASE WHEN aplica_multa::text='S' AND status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date < CURRENT_DATE
         THEN vl_titulo * (pct_multa/100.00) ELSE 0::numeric END AS vl_multa,
    CASE WHEN aplica_juros::text='S' AND status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date < CURRENT_DATE
         THEN vl_titulo * (pct_juros/100.00)/30.0 * (CURRENT_DATE - dt_vencto::date)::numeric ELSE 0::numeric END AS vl_juros,
    vl_titulo
      + CASE WHEN aplica_multa::text='S' AND status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date < CURRENT_DATE
             THEN vl_titulo * (pct_multa/100.00) ELSE 0::numeric END
      + CASE WHEN aplica_juros::text='S' AND status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date < CURRENT_DATE
             THEN vl_titulo * (pct_juros/100.00)/30.0 * (CURRENT_DATE - dt_vencto::date)::numeric ELSE 0::numeric END
      + vl_adicional + vl_despesa - vl_desconto - vl_pago AS vl_a_pagar,
    CASE
      WHEN status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date >= CURRENT_DATE AND vl_pago = 0 THEN 'A VENCER'
      WHEN status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date >= CURRENT_DATE AND vl_pago > 0 THEN 'PAGTO PARCIAL'
      WHEN status::text='A' AND dt_vencto IS NOT NULL AND dt_vencto::date < CURRENT_DATE THEN 'VENCIDO'
      WHEN status::text='B' THEN 'BAIXADO'
      WHEN status::text='C' THEN 'CANCELADO'
      ELSE 'INDEFINIDO'
    END AS situacao
FROM public.financeiro f;
