
CREATE TABLE IF NOT EXISTS public.produto_grupo (
  grupo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  empresa_id bigint NOT NULL DEFAULT 1,
  excluido boolean DEFAULT false,
  dt_cadastro timestamp with time zone DEFAULT now(),
  dt_alteracao timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subgrupo_produto (
  subgrupo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  grupo_id bigint NOT NULL,
  empresa_id bigint NOT NULL DEFAULT 1,
  excluido boolean DEFAULT false,
  dt_cadastro timestamp with time zone DEFAULT now(),
  dt_alteracao timestamp with time zone DEFAULT now()
);

ALTER TABLE public.produto
  ADD COLUMN IF NOT EXISTS nm_ecommerce varchar(80) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ds_ecommerce text NOT NULL DEFAULT '';

CREATE POLICY "Auth can view produto" ON public.produto
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth can insert produto" ON public.produto
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth can update produto" ON public.produto
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Auth can manage produto_grupo" ON public.produto_grupo
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Auth can manage subgrupo_produto" ON public.subgrupo_produto
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Auth can manage produto_codbarra" ON public.produto_codbarra
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
