
-- ================================================
-- NF-e: ENTRADA DE NOTAS FISCAIS
-- ================================================

-- ================================================
-- TABELA NFE_CABECALHO (Cabeçalho da NF-e de Entrada)
-- ================================================
CREATE TABLE public.NFE_CABECALHO (
  NFE_CABECALHO_ID  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID        BIGINT NOT NULL,
  CADASTRO_ID       BIGINT REFERENCES public.cadastro(cadastro_id),
  DEPOSITO_ID       BIGINT REFERENCES public.deposito(deposito_id),
  TP_ENTRADA        TEXT NOT NULL DEFAULT 'M' CHECK (TP_ENTRADA IN ('M', 'X')),
  ST_NF             TEXT NOT NULL DEFAULT 'A' CHECK (ST_NF IN ('A', 'C', 'E')),
  NR_NOTA           TEXT NOT NULL DEFAULT '',
  SERIE             TEXT NOT NULL DEFAULT '',
  DT_EMISSAO        DATE,
  DT_ENTRADA        DATE,
  DT_SAIDA          DATE,
  CHAVE_NFE         TEXT NOT NULL DEFAULT '',
  NR_PROTOCOLO      TEXT NOT NULL DEFAULT '',
  VL_PRODUTOS       NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_DESCONTO       NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_FRETE          NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_SEGURO         NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_DESPESA        NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_IPI            NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_ICMS_ST        NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_TOTAL_NF       NUMERIC(15,2) NOT NULL DEFAULT 0,
  OBS_NF            TEXT NOT NULL DEFAULT '',
  XML_NF            TEXT,
  EXCLUIDO          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IX_NFE_CABECALHO_EMPRESA        ON public.NFE_CABECALHO (EMPRESA_ID);
CREATE INDEX IX_NFE_CABECALHO_CADASTRO       ON public.NFE_CABECALHO (CADASTRO_ID);
CREATE INDEX IX_NFE_CABECALHO_DT_ENTRADA     ON public.NFE_CABECALHO (DT_ENTRADA);
CREATE UNIQUE INDEX IU_NFE_CABECALHO_CHAVE   ON public.NFE_CABECALHO (CHAVE_NFE) WHERE CHAVE_NFE <> '' AND EXCLUIDO = FALSE;

ALTER TABLE public.NFE_CABECALHO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read NFE_CABECALHO"
  ON public.NFE_CABECALHO FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert NFE_CABECALHO"
  ON public.NFE_CABECALHO FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update NFE_CABECALHO"
  ON public.NFE_CABECALHO FOR UPDATE TO authenticated USING (true);

CREATE TRIGGER TR_NFE_CABECALHO_UPDATED_AT
  BEFORE UPDATE ON public.NFE_CABECALHO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA NFE_ITEM (Itens da NF-e de Entrada)
-- ================================================
CREATE TABLE public.NFE_ITEM (
  NFE_ITEM_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NFE_CABECALHO_ID    BIGINT NOT NULL REFERENCES public.NFE_CABECALHO(NFE_CABECALHO_ID) ON DELETE CASCADE,
  EMPRESA_ID          BIGINT NOT NULL,
  PRODUTO_ID          BIGINT REFERENCES public.produto(produto_id),
  NR_ITEM             INTEGER NOT NULL DEFAULT 0,
  CD_PROD_FORNEC      TEXT NOT NULL DEFAULT '',
  NM_PRODUTO          TEXT NOT NULL DEFAULT '',
  NCM                 TEXT NOT NULL DEFAULT '',
  CFOP                TEXT NOT NULL DEFAULT '',
  UNIDADE             TEXT NOT NULL DEFAULT '',
  GTIN                TEXT NOT NULL DEFAULT '',
  QT_ENTRADA          NUMERIC(15,4) NOT NULL DEFAULT 0,
  VL_UNIT             NUMERIC(15,4) NOT NULL DEFAULT 0,
  VL_DESCONTO         NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_TOTAL            NUMERIC(15,2) NOT NULL DEFAULT 0,
  -- Impostos: valores
  VL_IPI              NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_ICMS_ST          NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_PIS              NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_COFINS           NUMERIC(15,2) NOT NULL DEFAULT 0,
  VL_FCP_ST           NUMERIC(15,2) NOT NULL DEFAULT 0,
  -- Impostos: alíquotas
  PC_IPI              NUMERIC(8,4) NOT NULL DEFAULT 0,
  PC_ICMS             NUMERIC(8,4) NOT NULL DEFAULT 0,
  PC_ICMS_ST          NUMERIC(8,4) NOT NULL DEFAULT 0,
  PC_PIS              NUMERIC(8,4) NOT NULL DEFAULT 0,
  PC_COFINS           NUMERIC(8,4) NOT NULL DEFAULT 0,
  PC_FCP_ST           NUMERIC(8,4) NOT NULL DEFAULT 0,
  -- CSTs
  CST_ICMS            TEXT NOT NULL DEFAULT '',
  CST_IPI             TEXT NOT NULL DEFAULT '',
  CST_PIS             TEXT NOT NULL DEFAULT '',
  CST_COFINS          TEXT NOT NULL DEFAULT '',
  -- MVA / ST
  PC_MVA              NUMERIC(8,4) NOT NULL DEFAULT 0,
  VL_BC_ST            NUMERIC(15,2) NOT NULL DEFAULT 0,
  EXCLUIDO            BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IX_NFE_ITEM_CABECALHO   ON public.NFE_ITEM (NFE_CABECALHO_ID);
CREATE INDEX IX_NFE_ITEM_PRODUTO      ON public.NFE_ITEM (PRODUTO_ID);
CREATE INDEX IX_NFE_ITEM_EMPRESA      ON public.NFE_ITEM (EMPRESA_ID);

ALTER TABLE public.NFE_ITEM ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read NFE_ITEM"
  ON public.NFE_ITEM FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert NFE_ITEM"
  ON public.NFE_ITEM FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update NFE_ITEM"
  ON public.NFE_ITEM FOR UPDATE TO authenticated USING (true);

CREATE TRIGGER TR_NFE_ITEM_UPDATED_AT
  BEFORE UPDATE ON public.NFE_ITEM
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();
