-- ============================================================
-- MOTOR DE REGRAS FISCAIS — SCRIPT COMPLETO E IDEMPOTENTE
-- Tabelas: cfop, tp_operacao, fiscal_regra,
--          fiscal_regra_cfop, fiscal_regra_item
-- Execute no Supabase SQL Editor (seguro rodar múltiplas vezes)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. CFOP
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cfop (
  cfop_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cd_cfop     varchar(10)  NOT NULL,
  descricao   text         NOT NULL,
  aplicacao   text,
  empresa_id  integer      DEFAULT 1 NOT NULL,
  excluido    boolean      DEFAULT false,
  dt_cadastro timestamptz  DEFAULT now(),
  dt_alteracao timestamptz
);

-- Garante coluna cd_cfop (caso tabela existia com nome "codigo")
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'cfop' AND column_name = 'codigo'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'cfop' AND column_name = 'cd_cfop'
  ) THEN
    ALTER TABLE public.cfop RENAME COLUMN codigo TO cd_cfop;
  END IF;
END $$;

-- Adiciona coluna aplicacao se não existir
ALTER TABLE public.cfop ADD COLUMN IF NOT EXISTS aplicacao text;

-- RLS + Policy
ALTER TABLE public.cfop ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cfop_all ON public.cfop;
CREATE POLICY cfop_all ON public.cfop
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON public.cfop TO authenticated, service_role;


-- ────────────────────────────────────────────────────────────
-- 2. TP_OPERACAO
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tp_operacao (
  tp_operacao_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao       text        NOT NULL,
  tp_movimento    varchar(1)  DEFAULT 'S',
  gera_financeiro varchar(1),
  gera_nf         varchar(1),
  gera_boleto     varchar(1),
  altera_estoque  varchar(1),
  valida_preco    varchar(1),
  plano_id        integer,
  empresa_id      integer     DEFAULT 1 NOT NULL,
  excluido        boolean     DEFAULT false,
  dt_cadastro     timestamptz DEFAULT now(),
  dt_alteracao    timestamptz
);

-- RLS + Policy
ALTER TABLE public.tp_operacao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tp_operacao_all ON public.tp_operacao;
CREATE POLICY tp_operacao_all ON public.tp_operacao
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON public.tp_operacao TO authenticated, service_role;


-- ────────────────────────────────────────────────────────────
-- 3. FISCAL_REGRA  (header da regra)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fiscal_regra (
  fiscal_regra_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao       text        NOT NULL,
  observacao      text,
  tp_operacao_id  int8        DEFAULT NULL,
  cfop_id         integer     REFERENCES public.cfop(cfop_id),
  regime_trib     varchar(30),          -- '*' | 'S' | 'L' | 'N'
  prioridade      integer     DEFAULT 0,
  vigencia_inicio date,
  vigencia_fim    date,
  empresa_id      integer     DEFAULT 1 NOT NULL,
  excluido        boolean     DEFAULT false,
  dt_cadastro     timestamptz DEFAULT now(),
  dt_alteracao    timestamptz
);

-- Adiciona colunas que podem estar faltando em bases antigas
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS observacao      text;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS tp_operacao_id  int8;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS cfop_id         integer REFERENCES public.cfop(cfop_id);
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS regime_trib     varchar(30);
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS prioridade      integer DEFAULT 0;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS vigencia_inicio date;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS vigencia_fim    date;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS excluido        boolean DEFAULT false;
ALTER TABLE public.fiscal_regra ADD COLUMN IF NOT EXISTS empresa_id      integer DEFAULT 1;

-- RLS + Policy
ALTER TABLE public.fiscal_regra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fiscal_regra_all ON public.fiscal_regra;
CREATE POLICY fiscal_regra_all ON public.fiscal_regra
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON public.fiscal_regra TO authenticated, service_role;

COMMENT ON TABLE  public.fiscal_regra IS 'Header das regras fiscais.';
COMMENT ON COLUMN public.fiscal_regra.regime_trib IS 'S=Simples Nacional, L=Lucro Presumido, N=Lucro Real, *=Todos';
COMMENT ON COLUMN public.fiscal_regra.tp_operacao_id IS 'FK para tp_operacao. NULL = aplica a todos os tipos.';


-- ────────────────────────────────────────────────────────────
-- 4. FISCAL_REGRA_CFOP  (CFOP resultante por filtro)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fiscal_regra_cfop (
  fiscal_regra_cfop_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fiscal_regra_id          integer NOT NULL REFERENCES public.fiscal_regra(fiscal_regra_id) ON DELETE CASCADE,
  cfop_id                  integer NOT NULL REFERENCES public.cfop(cfop_id),
  -- Filtros de aplicação
  uf_destino               varchar(2)  DEFAULT '*',
  cliente_contribuinte     boolean,
  cliente_consumidor_final boolean,
  ncm_filtro               varchar(10) DEFAULT '99999999',
  cest_filtro              varchar(10) DEFAULT '9999999',
  grupo_icms_id            integer,
  origem_produto           varchar(1),
  -- Metadados
  empresa_id               integer     DEFAULT 1 NOT NULL,
  dt_cadastro              timestamptz DEFAULT now(),
  dt_alteracao             timestamptz
);

ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS uf_destino               varchar(2)  DEFAULT '*';
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS cliente_contribuinte     boolean;
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS cliente_consumidor_final boolean;
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS ncm_filtro               varchar(10) DEFAULT '99999999';
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS cest_filtro              varchar(10) DEFAULT '9999999';
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS grupo_icms_id            integer;
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS origem_produto           varchar(1);
ALTER TABLE public.fiscal_regra_cfop ADD COLUMN IF NOT EXISTS empresa_id               integer DEFAULT 1;

-- RLS + Policy
ALTER TABLE public.fiscal_regra_cfop ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fiscal_regra_cfop_all ON public.fiscal_regra_cfop;
CREATE POLICY fiscal_regra_cfop_all ON public.fiscal_regra_cfop
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON public.fiscal_regra_cfop TO authenticated, service_role;

COMMENT ON TABLE  public.fiscal_regra_cfop IS 'CFOP resultante por combinação de filtros dentro de uma regra fiscal.';
COMMENT ON COLUMN public.fiscal_regra_cfop.ncm_filtro  IS '99999999 = wildcard (todos os NCMs).';
COMMENT ON COLUMN public.fiscal_regra_cfop.cest_filtro IS '9999999  = wildcard (todos os CESTs).';


-- ────────────────────────────────────────────────────────────
-- 5. FISCAL_REGRA_ITEM  (tributos por filtro)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fiscal_regra_item (
  fiscal_regra_item_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fiscal_regra_id          integer NOT NULL REFERENCES public.fiscal_regra(fiscal_regra_id) ON DELETE CASCADE,
  tipo_imposto             varchar(10) NOT NULL, -- ICMS | IPI | PIS | COFINS | CBSIBS
  -- Filtros de aplicação
  uf_destino               varchar(2)  DEFAULT '*',
  cliente_contribuinte     boolean,
  cliente_consumidor_final boolean,
  ncm_filtro               varchar(10) DEFAULT '99999999',
  cest_filtro              varchar(10) DEFAULT '9999999',
  grupo_icms_id            integer,
  origem_produto           varchar(1),
  -- Campos gerais de cálculo
  cst_csosn                varchar(3),
  aliquota                 numeric(10,4) DEFAULT 0,
  base_reducao             numeric(10,4) DEFAULT 0,
  motivo_desoneracao       integer,
  -- Simples Nacional
  p_cre_sn                 numeric(10,4) DEFAULT 0,
  -- ICMS-ST
  icms_st_aliquota         numeric(10,4) DEFAULT 0,
  icms_st_mva              numeric(10,4) DEFAULT 0,
  icms_st_base_reducao     numeric(10,4) DEFAULT 0,
  mod_bc                   integer       DEFAULT 3,
  mod_bc_st                integer       DEFAULT 4,
  -- IPI
  ipi_c_enq                varchar(3)    DEFAULT '999',
  -- PIS/COFINS
  cst_pis_cofins           varchar(3),
  nat_receita_pis_cofins   varchar(6),
  -- Reforma Tributária 2026
  ibs_aliquota             numeric(10,4) DEFAULT 0,
  cbs_aliquota             numeric(10,4) DEFAULT 0,
  is_aliquota              numeric(10,4) DEFAULT 0,
  -- Metadados
  empresa_id               integer       DEFAULT 1 NOT NULL,
  dt_cadastro              timestamptz   DEFAULT now(),
  dt_alteracao             timestamptz
);

ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS uf_destino               varchar(2)    DEFAULT '*';
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cliente_contribuinte     boolean;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cliente_consumidor_final boolean;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS ncm_filtro               varchar(10)   DEFAULT '99999999';
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cest_filtro              varchar(10)   DEFAULT '9999999';
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS grupo_icms_id            integer;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS origem_produto           varchar(1);
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cst_csosn                varchar(3);
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS aliquota                 numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS base_reducao             numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS motivo_desoneracao       integer;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS p_cre_sn                 numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS icms_st_aliquota         numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS icms_st_mva              numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS icms_st_base_reducao     numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS mod_bc                   integer       DEFAULT 3;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS mod_bc_st                integer       DEFAULT 4;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS ipi_c_enq                varchar(3)    DEFAULT '999';
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cst_pis_cofins           varchar(3);
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS nat_receita_pis_cofins   varchar(6);
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS ibs_aliquota             numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS cbs_aliquota             numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS is_aliquota              numeric(10,4) DEFAULT 0;
ALTER TABLE public.fiscal_regra_item ADD COLUMN IF NOT EXISTS empresa_id               integer       DEFAULT 1;

-- RLS + Policy
ALTER TABLE public.fiscal_regra_item ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fiscal_regra_item_all ON public.fiscal_regra_item;
CREATE POLICY fiscal_regra_item_all ON public.fiscal_regra_item
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT ALL ON public.fiscal_regra_item TO authenticated, service_role;

COMMENT ON TABLE  public.fiscal_regra_item IS 'Itens da regra fiscal: filtros + campos de cálculo por tributo.';
COMMENT ON COLUMN public.fiscal_regra_item.tipo_imposto IS 'ICMS | IPI | PIS | COFINS | CBSIBS';
COMMENT ON COLUMN public.fiscal_regra_item.ncm_filtro   IS '99999999 = wildcard (todos os NCMs).';
COMMENT ON COLUMN public.fiscal_regra_item.mod_bc       IS '0=MVA, 1=Pauta, 2=Preço Max, 3=Valor Op.';
COMMENT ON COLUMN public.fiscal_regra_item.mod_bc_st    IS '0=Preço Tab, 1=Pauta, 2=Preço Max, 3=Valor Op., 4=MVA';

-- ────────────────────────────────────────────────────────────
-- FIM DO SCRIPT
-- ────────────────────────────────────────────────────────────
