-- =============================================
-- MOTOR DE REGRAS FISCAIS — SCRIPT FINAL
-- fiscal_regra = header + filtros de nivel de regra
-- fiscal_regra_item = filtros especificos + calculo por tributo
-- =============================================

-- 1. CRIAR fiscal_regra (header)
CREATE TABLE IF NOT EXISTS public.fiscal_regra (
    fiscal_regra_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao         text NOT NULL,
    observacao        text,
    tipo_operacao_id  integer REFERENCES public.tipo_operacao(tipo_operacao_id),
    cfop_id           integer REFERENCES public.cfop(cfop_id),
    regime_trib       varchar(1),  -- 'S'=Simples Nacional; 'L'=Lucro Presumido; 'N'=Lucro Real; NULL=todos
    prioridade        integer DEFAULT 0,
    vigencia_inicio   date,
    vigencia_fim      date,
    empresa_id        integer DEFAULT 1 NOT NULL,
    excluido          boolean DEFAULT false,
    dt_cadastro       timestamp with time zone DEFAULT now(),
    dt_alteracao      timestamp with time zone
);

ALTER TABLE public.fiscal_regra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fiscal_regra_all" ON public.fiscal_regra;
CREATE POLICY "fiscal_regra_all" ON public.fiscal_regra
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE  public.fiscal_regra IS 'Header das regras fiscais. Agrupa itens por tipo de operacao, CRT e vigencia.';
COMMENT ON COLUMN public.fiscal_regra.regime_trib IS 'S=Simples Nacional; L=Lucro Presumido; N=Lucro Real; NULL=aplica a todos os regimes.'; 

-- 2. CRIAR fiscal_regra_item (filtros especificos + calculo)
-- Cada item combina: para qual situacao se aplica (filtros) + como calcular (CST, aliquota etc)
CREATE TABLE IF NOT EXISTS public.fiscal_regra_item (
    fiscal_regra_item_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_regra_id          integer NOT NULL REFERENCES public.fiscal_regra(fiscal_regra_id) ON DELETE CASCADE,
    tipo_imposto             varchar(10) NOT NULL,
    -- Valores: 'ICMS' | 'IPI' | 'PIS' | 'COFINS' | 'IBS' | 'CBS' | 'IS'

    -- Filtros de aplicacao deste item (quando esta linha entra em acao)
    uf_destino               varchar(2)  DEFAULT '*',        -- '*' = todos os estados
    cliente_contribuinte     boolean,                        -- true/false/NULL=todos
    cliente_consumidor_final boolean,                        -- true/false/NULL=todos
    ncm_filtro               varchar(10) DEFAULT '99999999', -- 9s = regra geral (wildcard)
    cest_filtro              varchar(10) DEFAULT '9999999',  -- 9s = regra geral (wildcard)
    grupo_icms_id            integer,                        -- NULL = todos os grupos
    origem_produto           varchar(1),                     -- 0=Nacional; 1=Import; NULL=todos

    -- Campos gerais de calculo
    cst_csosn                varchar(3),   -- CST (Regime Normal) ou CSOSN (Simples)
    aliquota                 numeric(10,4) DEFAULT 0,
    base_reducao             numeric(10,4) DEFAULT 0,
    motivo_desoneracao       integer,

    -- Simples Nacional
    p_cre_sn                 numeric(10,4) DEFAULT 0, -- pCredSN

    -- ICMS-ST
    icms_st_aliquota         numeric(10,4) DEFAULT 0,
    icms_st_mva              numeric(10,4) DEFAULT 0, -- sobrepos ao MVA do produto se > 0
    icms_st_base_reducao     numeric(10,4) DEFAULT 0,
    mod_bc                   integer DEFAULT 3,  -- 0-MVA; 1-Pauta; 2-Preco Max; 3-Valor Op.
    mod_bc_st                integer DEFAULT 4,

    -- IPI
    ipi_c_enq                varchar(3) DEFAULT '999',

    -- PIS/COFINS
    cst_pis_cofins           varchar(3),
    nat_receita_pis_cofins   varchar(6),

    -- Reforma Tributaria 2026+
    ibs_aliquota             numeric(10,4) DEFAULT 0,
    cbs_aliquota             numeric(10,4) DEFAULT 0,
    is_aliquota              numeric(10,4) DEFAULT 0,

    empresa_id               integer DEFAULT 1 NOT NULL,
    dt_cadastro              timestamp with time zone DEFAULT now(),
    dt_alteracao             timestamp with time zone
);

ALTER TABLE public.fiscal_regra_item ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fiscal_regra_item_all" ON public.fiscal_regra_item;
CREATE POLICY "fiscal_regra_item_all" ON public.fiscal_regra_item
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE  public.fiscal_regra_item IS 'Itens da regra fiscal. Cada linha define filtros de aplicacao + campos de calculo para um tributo.';
COMMENT ON COLUMN public.fiscal_regra_item.tipo_imposto  IS 'ICMS | IPI | PIS | COFINS | IBS | CBS | IS';
COMMENT ON COLUMN public.fiscal_regra_item.ncm_filtro    IS '99999999 (todos 9s) = wildcard geral. Valor especifico sobrep a regra geral.';
COMMENT ON COLUMN public.fiscal_regra_item.cest_filtro   IS '9999999 (todos 9s) = wildcard geral. Valor especifico sobrep a regra geral.';
COMMENT ON COLUMN public.fiscal_regra_item.icms_st_mva   IS 'MVA da regra. Sobrep ao MVA do produto se > 0.';

-- 3. Campos fiscais na EMPRESA
ALTER TABLE public.empresa
    ADD COLUMN IF NOT EXISTS pc_icms_interestadual numeric(10,4) DEFAULT 12,
    ADD COLUMN IF NOT EXISTS pc_fcp_empresa        numeric(10,4) DEFAULT 0;

COMMENT ON COLUMN public.empresa.pc_icms_interestadual IS 'Aliquota ICMS interestadual das saidas desta empresa (ex: 12). CRT derivado de regime_trib: S=1, L/N=3.';
COMMENT ON COLUMN public.empresa.pc_fcp_empresa        IS 'FCP do estado sede da empresa (para DIFAL interno).';

-- 4. Campos complementares no ESTADO
ALTER TABLE public.estado
    ADD COLUMN IF NOT EXISTS pc_fcp_st          numeric(10,4) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reducao_bc_interna numeric(10,4) DEFAULT 0;

COMMENT ON COLUMN public.estado.icms_interno       IS 'Aliquota ICMS interna (operacoes dentro do estado).';
COMMENT ON COLUMN public.estado.icms_externo       IS 'Aliquota ICMS interestadual de entrada (fallback).';
COMMENT ON COLUMN public.estado.pc_fcp             IS 'FCP - Fundo de Combate a Pobreza (%).';
COMMENT ON COLUMN public.estado.pc_fcp_st          IS 'FCP-ST na Substituicao Tributaria.';
COMMENT ON COLUMN public.estado.reducao_bc_interna IS 'Reducao percentual da BC ICMS interno padrao do estado.';

-- 5. CRIAR fiscal_regra_cfop
-- Determina o CFOP resultante a partir dos mesmos filtros de fiscal_regra_item.
-- O motor busca o CFOP mais especifico (maior score NCM+CEST+UF) para a operacao.
CREATE TABLE IF NOT EXISTS public.fiscal_regra_cfop (
    fiscal_regra_cfop_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_regra_id          integer NOT NULL REFERENCES public.fiscal_regra(fiscal_regra_id) ON DELETE CASCADE,

    -- CFOP resultante (carrega descricao da tabela cfop)
    cfop_id                  integer NOT NULL REFERENCES public.cfop(cfop_id),

    -- Filtros de aplicacao (mesma convencao de fiscal_regra_item)
    uf_destino               varchar(2)  DEFAULT '*',        -- '*' = todos os estados
    cliente_contribuinte     boolean,                        -- true/false/NULL=todos
    cliente_consumidor_final boolean,                        -- true/false/NULL=todos
    ncm_filtro               varchar(10) DEFAULT '99999999', -- 9s = wildcard geral
    cest_filtro              varchar(10) DEFAULT '9999999',  -- 9s = wildcard geral
    grupo_icms_id            integer,                        -- NULL = todos os grupos
    origem_produto           varchar(1),                     -- 0=Nacional; 1=Import; NULL=todos

    empresa_id               integer DEFAULT 1 NOT NULL,
    dt_cadastro              timestamp with time zone DEFAULT now(),
    dt_alteracao             timestamp with time zone
);

ALTER TABLE public.fiscal_regra_cfop ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "fiscal_regra_cfop_all" ON public.fiscal_regra_cfop;
CREATE POLICY "fiscal_regra_cfop_all" ON public.fiscal_regra_cfop
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE  public.fiscal_regra_cfop IS 'CFOP resultante por combinacao de filtros dentro de uma regra fiscal. O motor seleciona o registro de maior especificidade (NCM+CEST+UF).';
COMMENT ON COLUMN public.fiscal_regra_cfop.cfop_id    IS 'FK para tabela cfop. Carrega codigo e descricao do CFOP aplicavel.';
COMMENT ON COLUMN public.fiscal_regra_cfop.ncm_filtro IS '99999999 (todos 9s) = wildcard geral. Valor especifico tem prioridade maior.';
COMMENT ON COLUMN public.fiscal_regra_cfop.cest_filtro IS '9999999 (todos 9s) = wildcard geral. Valor especifico tem prioridade maior.';
