
-- =============================================
-- PART 1: EMPRESA + CORE TABLES (tables that others reference)
-- =============================================

-- EMPRESA
CREATE TABLE IF NOT EXISTS public.empresa (
    empresa_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social text DEFAULT 'Empresa Padrão' NOT NULL,
    nome_fantasia text DEFAULT '' NOT NULL,
    cnpj character varying(18) DEFAULT '' NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now()
);

-- AUDITORIA
CREATE TABLE IF NOT EXISTS public.auditoria (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    xtabela text NOT NULL,
    xregistro_id text NOT NULL,
    xacao text NOT NULL,
    xdados_anteriores jsonb,
    xdados_novos jsonb,
    xusuario_id uuid,
    xdt_auditoria timestamp with time zone DEFAULT now(),
    xip text DEFAULT '' NOT NULL,
    xobs text DEFAULT '' NOT NULL
);

-- BANCO
CREATE TABLE IF NOT EXISTS public.banco (
    banco_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    razao_social text DEFAULT '' NOT NULL,
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- CIDADE
CREATE TABLE IF NOT EXISTS public.cidade (
    cidade_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao text NOT NULL,
    uf character varying(2) DEFAULT 'PR',
    empresa_id integer DEFAULT 1 NOT NULL,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone
);

-- GRUPO_CADASTRO
CREATE TABLE IF NOT EXISTS public.grupo_cadastro (
    grupo_cadastro_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    nome character varying NOT NULL,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now(),
    excluido boolean DEFAULT false
);

-- PRODUTO_GRUPO
CREATE TABLE IF NOT EXISTS public.produto_grupo (
    grupo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    nome character varying(50) NOT NULL,
    ultima_sequencia integer DEFAULT 0,
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now()
);

-- CADASTRO
CREATE TABLE IF NOT EXISTS public.cadastro (
    cadastro_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    cnpj character varying(18) DEFAULT '' NOT NULL,
    razao_social character varying(60) NOT NULL,
    nome_fantasia character varying(60) DEFAULT '' NOT NULL,
    identificacao character varying(40) DEFAULT '' NOT NULL,
    nome_curto character varying(60) DEFAULT '' NOT NULL,
    endereco_cidade_id integer,
    endereco_logradouro character varying(60) DEFAULT '' NOT NULL,
    endereco_numero character varying(10) DEFAULT '' NOT NULL,
    endereco_bairro character varying(40) DEFAULT '' NOT NULL,
    endereco_cep character varying(10) DEFAULT '' NOT NULL,
    fone_geral character varying(15) DEFAULT '' NOT NULL,
    fone_comercial character varying(15) DEFAULT '' NOT NULL,
    tp_pessoa character varying(1) DEFAULT 'F',
    grupo_cadastro_id integer,
    st_cadastro character varying(1) DEFAULT 'A',
    dep_nome1 character varying(60) DEFAULT '' NOT NULL,
    dep_nome2 character varying(60) DEFAULT '' NOT NULL,
    dep_nome3 character varying(60) DEFAULT '' NOT NULL,
    dep_dt_nasc1 timestamp with time zone,
    dep_dt_nasc2 timestamp with time zone,
    dep_dt_nasc3 timestamp with time zone,
    dep_telefone1 character varying(16) DEFAULT '' NOT NULL,
    dep_telefone2 character varying(16) DEFAULT '' NOT NULL,
    dep_telefone3 character varying(16) DEFAULT '' NOT NULL,
    dep_email1 character varying(120) DEFAULT '' NOT NULL,
    dep_email2 character varying(120) DEFAULT '' NOT NULL,
    dep_email3 character varying(120) DEFAULT '' NOT NULL,
    dep_cpf1 character varying(18) DEFAULT '' NOT NULL,
    dep_cpf2 character varying(18) DEFAULT '' NOT NULL,
    dep_cpf3 character varying(18) DEFAULT '' NOT NULL,
    dep_st1 character(1) DEFAULT 'S',
    dep_st2 character(1) DEFAULT 'N',
    dep_st3 character(1) DEFAULT 'N',
    dt_nasc timestamp with time zone,
    email character varying(120) DEFAULT '' NOT NULL,
    st_cliente character(1) DEFAULT 'S',
    st_vendedor character(1) DEFAULT 'N',
    st_fornecedor character(1) DEFAULT 'N',
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now(),
    inscricao_estadual character varying DEFAULT '' NOT NULL,
    fone_financeiro character varying DEFAULT '' NOT NULL,
    fone_faturamento character varying DEFAULT '' NOT NULL,
    condicao_id integer,
    funcionario_id integer,
    tp_contribuinte character varying DEFAULT 'N',
    tp_cadastro_id integer,
    estado_civil character varying DEFAULT '' NOT NULL,
    conj_nome character varying DEFAULT '' NOT NULL,
    conj_cpf character varying DEFAULT '' NOT NULL,
    conj_dt_nasc timestamp with time zone,
    conj_telefone character varying DEFAULT '' NOT NULL,
    rg character varying DEFAULT '' NOT NULL,
    nacionalidade character varying DEFAULT 'BRASILEIRA',
    portador_id integer,
    rota_id integer,
    rota_seq integer DEFAULT 0 NOT NULL,
    dep_grau_parent1 character varying DEFAULT '' NOT NULL,
    dep_grau_parent2 character varying DEFAULT '' NOT NULL,
    tabela_preco_id integer,
    inscricao_municipal character varying DEFAULT '' NOT NULL,
    tipo_cadastro character varying DEFAULT 'A',
    endereco_compl character varying DEFAULT '' NOT NULL,
    endereco_ptoref character varying DEFAULT '' NOT NULL,
    st_transportador character varying DEFAULT 'N'
);

-- PRODUTO
CREATE TABLE IF NOT EXISTS public.produto (
    produto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint DEFAULT 1 NOT NULL,
    grupo_id bigint,
    nome character varying(80) NOT NULL,
    nome_reduzido character varying(80) DEFAULT '' NOT NULL,
    descricao text DEFAULT '' NOT NULL,
    unidade_id character varying(5) DEFAULT 'UN',
    gtin character varying(14) DEFAULT '' NOT NULL,
    referencia character varying(20) DEFAULT '' NOT NULL,
    tp_produto character varying(2) DEFAULT 'PA',
    ativo character varying(1) DEFAULT 'S',
    preco_venda numeric(14,4) DEFAULT 0,
    preco_promocional numeric(14,4) DEFAULT 0 NOT NULL,
    vl_compra numeric(12,2) DEFAULT 0,
    pc_markup numeric(10,2) DEFAULT 0,
    preco_sugerido numeric(14,4) DEFAULT 0,
    url_foto text DEFAULT '' NOT NULL,
    venda_online boolean DEFAULT true,
    dias_venda_online text DEFAULT '0,1,2,3,4',
    controla_estoque character varying(1) DEFAULT 'S',
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now()
);
