
-- ================================================
-- CONTROLE DE ACESSO - SCHEMA COMPLETO
-- ================================================

-- Função para atualizar timestamps
CREATE OR REPLACE FUNCTION public.FU_UPDATE_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- ================================================
-- TABELA PERFIL (Perfis de acesso)
-- ================================================
CREATE TABLE public.PERFIL (
  PERFIL_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  NM_PERFIL TEXT NOT NULL,
  FL_ADMINISTRADOR BOOLEAN NOT NULL DEFAULT FALSE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_EMPRESA_NOME ON public.PERFIL (EMPRESA_ID, NM_PERFIL) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_EMPRESA ON public.PERFIL (EMPRESA_ID);

ALTER TABLE public.PERFIL ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL"
  ON public.PERFIL FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL"
  ON public.PERFIL FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL"
  ON public.PERFIL FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA PERFIL_USUARIO (Associação usuario-perfil)
-- ================================================
CREATE TABLE public.PERFIL_USUARIO (
  PERFIL_USUARIO_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  PERFIL_ID BIGINT NOT NULL REFERENCES public.PERFIL(PERFIL_ID) ON DELETE CASCADE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_USUARIO ON public.PERFIL_USUARIO (EMPRESA_ID, user_id, PERFIL_ID) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_USUARIO_USER ON public.PERFIL_USUARIO (user_id);
CREATE INDEX IX_PERFIL_USUARIO_PERFIL ON public.PERFIL_USUARIO (PERFIL_ID);

ALTER TABLE public.PERFIL_USUARIO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL_USUARIO"
  ON public.PERFIL_USUARIO FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL_USUARIO"
  ON public.PERFIL_USUARIO FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL_USUARIO"
  ON public.PERFIL_USUARIO FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_USUARIO_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL_USUARIO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA EMPRESA_USUARIO (Associação usuario-empresa)
-- ================================================
CREATE TABLE public.EMPRESA_USUARIO (
  EMPRESA_USUARIO_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_EMPRESA_USUARIO ON public.EMPRESA_USUARIO (EMPRESA_ID, user_id) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_EMPRESA_USUARIO_USER ON public.EMPRESA_USUARIO (user_id);

ALTER TABLE public.EMPRESA_USUARIO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read EMPRESA_USUARIO"
  ON public.EMPRESA_USUARIO FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert EMPRESA_USUARIO"
  ON public.EMPRESA_USUARIO FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update EMPRESA_USUARIO"
  ON public.EMPRESA_USUARIO FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_EMPRESA_USUARIO_UPDATED_AT
  BEFORE UPDATE ON public.EMPRESA_USUARIO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA PERFIL_ACESSO_MENU (Controle de menus)
-- ================================================
CREATE TABLE public.PERFIL_ACESSO_MENU (
  PERFIL_ACESSO_MENU_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  PERFIL_ID BIGINT NOT NULL REFERENCES public.PERFIL(PERFIL_ID) ON DELETE CASCADE,
  NM_MENU TEXT NOT NULL,
  NM_MENU_PAI TEXT,
  FL_VISIVEL BOOLEAN NOT NULL DEFAULT FALSE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_ACESSO_MENU ON public.PERFIL_ACESSO_MENU (EMPRESA_ID, PERFIL_ID, NM_MENU) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_ACESSO_MENU_PERFIL ON public.PERFIL_ACESSO_MENU (PERFIL_ID);

ALTER TABLE public.PERFIL_ACESSO_MENU ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL_ACESSO_MENU"
  ON public.PERFIL_ACESSO_MENU FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL_ACESSO_MENU"
  ON public.PERFIL_ACESSO_MENU FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL_ACESSO_MENU"
  ON public.PERFIL_ACESSO_MENU FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_ACESSO_MENU_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL_ACESSO_MENU
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA PERFIL_ACESSO_FORMULARIO (Controle de formulários)
-- ================================================
CREATE TABLE public.PERFIL_ACESSO_FORMULARIO (
  PERFIL_ACESSO_FORMULARIO_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  PERFIL_ID BIGINT NOT NULL REFERENCES public.PERFIL(PERFIL_ID) ON DELETE CASCADE,
  NM_FORMULARIO TEXT NOT NULL,
  FL_VISUALIZAR BOOLEAN NOT NULL DEFAULT TRUE,
  FL_INCLUIR BOOLEAN NOT NULL DEFAULT FALSE,
  FL_ALTERAR BOOLEAN NOT NULL DEFAULT FALSE,
  FL_EXCLUIR_REGISTRO BOOLEAN NOT NULL DEFAULT FALSE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_ACESSO_FORMULARIO ON public.PERFIL_ACESSO_FORMULARIO (EMPRESA_ID, PERFIL_ID, NM_FORMULARIO) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_ACESSO_FORM_PERFIL ON public.PERFIL_ACESSO_FORMULARIO (PERFIL_ID);

ALTER TABLE public.PERFIL_ACESSO_FORMULARIO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL_ACESSO_FORMULARIO"
  ON public.PERFIL_ACESSO_FORMULARIO FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL_ACESSO_FORMULARIO"
  ON public.PERFIL_ACESSO_FORMULARIO FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL_ACESSO_FORMULARIO"
  ON public.PERFIL_ACESSO_FORMULARIO FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_ACESSO_FORM_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL_ACESSO_FORMULARIO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA PERFIL_ACESSO_BOTAO (Controle de botões)
-- ================================================
CREATE TABLE public.PERFIL_ACESSO_BOTAO (
  PERFIL_ACESSO_BOTAO_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  PERFIL_ID BIGINT NOT NULL REFERENCES public.PERFIL(PERFIL_ID) ON DELETE CASCADE,
  NM_FORMULARIO TEXT NOT NULL,
  NM_BOTAO TEXT NOT NULL,
  FL_EDITAVEL BOOLEAN NOT NULL DEFAULT TRUE,
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_ACESSO_BOTAO ON public.PERFIL_ACESSO_BOTAO (EMPRESA_ID, PERFIL_ID, NM_FORMULARIO, NM_BOTAO) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_ACESSO_BOTAO_PERFIL ON public.PERFIL_ACESSO_BOTAO (PERFIL_ID);

ALTER TABLE public.PERFIL_ACESSO_BOTAO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL_ACESSO_BOTAO"
  ON public.PERFIL_ACESSO_BOTAO FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL_ACESSO_BOTAO"
  ON public.PERFIL_ACESSO_BOTAO FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL_ACESSO_BOTAO"
  ON public.PERFIL_ACESSO_BOTAO FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_ACESSO_BOTAO_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL_ACESSO_BOTAO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- TABELA PERFIL_ACESSO_CAMPO (Controle de campos)
-- ================================================
CREATE TABLE public.PERFIL_ACESSO_CAMPO (
  PERFIL_ACESSO_CAMPO_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMPRESA_ID BIGINT NOT NULL,
  PERFIL_ID BIGINT NOT NULL REFERENCES public.PERFIL(PERFIL_ID) ON DELETE CASCADE,
  NM_FORMULARIO TEXT NOT NULL,
  NM_CAMPO TEXT NOT NULL,
  TP_EDITAVEL TEXT NOT NULL DEFAULT 'EDITAVEL' CHECK (TP_EDITAVEL IN ('NAO_EDITAVEL', 'EDITAVEL_INCLUSAO', 'EDITAVEL_ALTERACAO', 'EDITAVEL')),
  FL_EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IU_PERFIL_ACESSO_CAMPO ON public.PERFIL_ACESSO_CAMPO (EMPRESA_ID, PERFIL_ID, NM_FORMULARIO, NM_CAMPO) WHERE FL_EXCLUIDO = FALSE;
CREATE INDEX IX_PERFIL_ACESSO_CAMPO_PERFIL ON public.PERFIL_ACESSO_CAMPO (PERFIL_ID);

ALTER TABLE public.PERFIL_ACESSO_CAMPO ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read PERFIL_ACESSO_CAMPO"
  ON public.PERFIL_ACESSO_CAMPO FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert PERFIL_ACESSO_CAMPO"
  ON public.PERFIL_ACESSO_CAMPO FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update PERFIL_ACESSO_CAMPO"
  ON public.PERFIL_ACESSO_CAMPO FOR UPDATE TO authenticated
  USING (true);

CREATE TRIGGER TR_PERFIL_ACESSO_CAMPO_UPDATED_AT
  BEFORE UPDATE ON public.PERFIL_ACESSO_CAMPO
  FOR EACH ROW EXECUTE FUNCTION public.FU_UPDATE_UPDATED_AT();

-- ================================================
-- FUNCTION: Verificar se usuario é admin
-- ================================================
CREATE OR REPLACE FUNCTION public.FU_IS_ADMIN(_user_id UUID, _empresa_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.PERFIL_USUARIO pu
    JOIN public.PERFIL p ON p.PERFIL_ID = pu.PERFIL_ID AND p.EMPRESA_ID = pu.EMPRESA_ID
    WHERE pu.user_id = _user_id
      AND pu.EMPRESA_ID = _empresa_id
      AND pu.FL_EXCLUIDO = FALSE
      AND p.FL_ADMINISTRADOR = TRUE
      AND p.FL_EXCLUIDO = FALSE
  )
$$;

-- ================================================
-- FUNCTION: Verificar visibilidade de menu
-- ================================================
CREATE OR REPLACE FUNCTION public.FU_MENU_VISIVEL(_user_id UUID, _empresa_id BIGINT, _nm_menu TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    CASE 
      WHEN public.FU_IS_ADMIN(_user_id, _empresa_id) THEN TRUE
      ELSE COALESCE((
        SELECT pam.FL_VISIVEL
        FROM public.PERFIL_ACESSO_MENU pam
        JOIN public.PERFIL_USUARIO pu ON pu.PERFIL_ID = pam.PERFIL_ID AND pu.EMPRESA_ID = pam.EMPRESA_ID
        WHERE pu.user_id = _user_id
          AND pam.EMPRESA_ID = _empresa_id
          AND pam.NM_MENU = _nm_menu
          AND pam.FL_EXCLUIDO = FALSE
          AND pu.FL_EXCLUIDO = FALSE
        ORDER BY pam.FL_VISIVEL DESC
        LIMIT 1
      ), FALSE)
    END
$$;

-- ================================================
-- FUNCTION: Verificar permissão de formulário
-- ================================================
CREATE OR REPLACE FUNCTION public.FU_FORM_PERMISSAO(
  _user_id UUID, 
  _empresa_id BIGINT, 
  _nm_formulario TEXT
)
RETURNS TABLE(FL_VISUALIZAR BOOLEAN, FL_INCLUIR BOOLEAN, FL_ALTERAR BOOLEAN, FL_EXCLUIR_REGISTRO BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    CASE WHEN public.FU_IS_ADMIN(_user_id, _empresa_id) THEN TRUE
    ELSE COALESCE(bool_or(paf.FL_VISUALIZAR), TRUE) END,
    CASE WHEN public.FU_IS_ADMIN(_user_id, _empresa_id) THEN TRUE
    ELSE COALESCE(bool_or(paf.FL_INCLUIR), FALSE) END,
    CASE WHEN public.FU_IS_ADMIN(_user_id, _empresa_id) THEN TRUE
    ELSE COALESCE(bool_or(paf.FL_ALTERAR), FALSE) END,
    CASE WHEN public.FU_IS_ADMIN(_user_id, _empresa_id) THEN TRUE
    ELSE COALESCE(bool_or(paf.FL_EXCLUIR_REGISTRO), FALSE) END
  FROM public.PERFIL_ACESSO_FORMULARIO paf
  JOIN public.PERFIL_USUARIO pu ON pu.PERFIL_ID = paf.PERFIL_ID AND pu.EMPRESA_ID = paf.EMPRESA_ID
  WHERE pu.user_id = _user_id
    AND paf.EMPRESA_ID = _empresa_id
    AND paf.NM_FORMULARIO = _nm_formulario
    AND paf.FL_EXCLUIDO = FALSE
    AND pu.FL_EXCLUIDO = FALSE
$$;
