-- Migration: Create produto_fator_conversao table and add nfe tracking columns to movimento_item

CREATE TABLE IF NOT EXISTS public.produto_fator_conversao (
    produto_fator_conversao_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id bigint NOT NULL DEFAULT 1,
    produto_id bigint NOT NULL REFERENCES public.produto(produto_id) ON DELETE CASCADE,
    unidade_entrada_id varchar(10) NOT NULL,
    unidade_saida_id varchar(10) NOT NULL,
    fator_conversao numeric(15, 4) NOT NULL CHECK (fator_conversao > 0),
    tp_funcao character(1) NOT NULL DEFAULT 'M' CHECK (tp_funcao IN ('M', 'D')),
    excluido boolean DEFAULT false,
    dt_cadastro timestamp with time zone DEFAULT now(),
    dt_alteracao timestamp with time zone DEFAULT now(),
    CONSTRAINT produto_fator_conversao_uk UNIQUE (empresa_id, produto_id, unidade_entrada_id, unidade_saida_id, tp_funcao)
);

-- RLS & Policies
ALTER TABLE public.produto_fator_conversao ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'produto_fator_conversao' AND policyname = 'Auth can manage produto_fator_conversao'
    ) THEN
        CREATE POLICY "Auth can manage produto_fator_conversao" ON public.produto_fator_conversao TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

GRANT ALL ON TABLE public.produto_fator_conversao TO anon, authenticated;

-- Adicionar colunas de rastreabilidade fiscal de NFe no movimento_item caso não existam
ALTER TABLE public.movimento_item ADD COLUMN IF NOT EXISTS qt_original_nfe numeric(15, 4);
ALTER TABLE public.movimento_item ADD COLUMN IF NOT EXISTS unidade_original_nfe varchar(20);
