// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zicapdmkddpllxniupgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppY2FwZG1rZGRwbGx4bml1cGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNjE3MTYsImV4cCI6MjA5MDgzNzcxNn0.hqOi69cdFzB_G_JpWS-UvdusCKpeATSMOxci0dEas78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});